import type { CourseModuleContent } from "./types";

export const phaseThreeModules: CourseModuleContent[] = [
  {
    number: "11",
    slug: "grabacion",
    title: "Grabación",
    phase: "Producción y plataformas",
    phaseNumber: "03",
    duration: "4 h 15 min",
    promise: "Grabar contenido claro y profesional con un sistema simple de luz, audio, composición y dirección frente a cámara.",
    summary: "La calidad que más importa es la que facilita comprender y confiar. No necesitas un estudio costoso; necesitas controlar luz, sonido, encuadre, energía y repetición. Diseñarás un espacio mínimo, una rutina de preparación y un flujo de grabación por lotes que reduzca errores y preserve naturalidad.",
    outcomes: [
      "Configurar un set mínimo con teléfono, luz estable y audio limpio.",
      "Elegir planos y composición según intención del contenido.",
      "Mejorar presencia, dicción y conexión con la cámara.",
      "Grabar varias piezas en una sesión con un protocolo de calidad.",
    ],
    lessons: [
      {
        number: "11.1",
        title: "El set mínimo que sí importa",
        duration: "55 min",
        objective: "Priorizar inversión y configuración por impacto perceptible.",
        concept: "El orden de mejora suele ser mensaje, audio, luz, estabilidad y cámara. Un teléfono reciente con buena luz y sonido supera a una cámara cara mal utilizada. Reduce eco, limpia el lente, bloquea exposición y enfoque cuando sea posible, y coloca el micrófono cerca. Construye un set repetible para no reinventar cada grabación.",
        framework: [
          "Audio: cercanía, ruido controlado y prueba con auriculares.",
          "Luz: fuente suave a 45 grados y separación del fondo.",
          "Estabilidad: trípode y altura de lente cercana a los ojos.",
          "Cámara: resolución consistente, lente limpia y espacio de almacenamiento.",
        ],
        example: "Una ventana lateral, cortina translúcida, teléfono en trípode y micrófono de solapa pueden producir una imagen más creíble que luces decorativas con voz lejana y eco.",
        practice: "Graba el mismo texto en cuatro configuraciones cambiando una variable: distancia del micrófono, orientación de la luz, distancia al fondo y altura de cámara. Compara con auriculares y pantalla pequeña.",
        deliverable: "Diagrama de set, configuración base y prueba técnica aprobada.",
      },
      {
        number: "11.2",
        title: "Composición y lenguaje visual",
        duration: "60 min",
        objective: "Usar encuadre, fondo y movimiento para apoyar la intención del mensaje.",
        concept: "El encuadre comunica antes de que hables. Un plano cerrado aumenta intensidad; uno medio permite gestos; mostrar proceso aporta evidencia. El fondo debe añadir contexto o permanecer silencioso. Deja espacio para subtítulos y elementos de interfaz, especialmente en vertical.",
        framework: [
          "Plano: cerrado para emoción, medio para enseñanza, abierto para demostración.",
          "Fondo: profundidad, orden y elementos que refuercen identidad.",
          "Mirada: lente para conversación; fuera de cámara para reflexión o entrevista.",
          "B-roll: acciones y detalles que prueban lo que estás explicando.",
        ],
        example: "En un tutorial, alterna plano medio al explicar, detalle de manos al demostrar y captura de pantalla para el proceso. Cada cambio responde a una necesidad de comprensión.",
        practice: "Diseña una lista de seis planos reutilizables para tu marca. Graba una secuencia de 30 segundos con plano principal, recurso y demostración sin transiciones digitales.",
        deliverable: "Biblioteca de seis encuadres y lista de B-roll recurrente.",
      },
      {
        number: "11.3",
        title: "Presencia y dirección frente a cámara",
        duration: "65 min",
        objective: "Transmitir intención y naturalidad sin memorizar cada palabra.",
        concept: "La presencia mejora cuando sabes a quién hablas y qué quieres que sienta o entienda. Mira la lente como si fuera una persona específica. Ensaya bloques de ideas, no una actuación perfecta. La energía de cámara necesita ser ligeramente más clara que una conversación normal, sin convertirse en personaje.",
        framework: [
          "Intención: una emoción y una decisión para la audiencia.",
          "Respiración: exhala antes de comenzar y deja pausas editables.",
          "Énfasis: cambia ritmo y volumen en palabras clave.",
          "Repetición útil: graba tres versiones con intenciones distintas.",
        ],
        example: "Primera toma: explicar. Segunda: advertir. Tercera: acompañar. Aunque el texto sea igual, la intención revela qué tono sostiene mejor el mensaje.",
        practice: "Graba un minuto durante cinco días. Evalúa mirada, ritmo, muletillas, postura y claridad, pero corrige una sola variable por día.",
        deliverable: "Registro de cinco tomas y protocolo de preparación de diez minutos.",
      },
      {
        number: "11.4",
        title: "Producción por lotes y control de calidad",
        duration: "75 min",
        objective: "Grabar varias piezas sin perder energía, continuidad ni archivos.",
        concept: "Una sesión eficiente comienza antes de encender la cámara. Ordena guiones por set y energía, prepara nombres de archivo, verifica batería y almacenamiento, y realiza prueba de diez segundos. Graba aperturas adicionales cuando tu energía está alta y registra notas de edición inmediatamente.",
        framework: [
          "Preparación: guiones, vestuario, utilería, equipo y ambiente.",
          "Orden: piezas exigentes primero, luego variaciones y B-roll.",
          "Continuidad: exposición, audio, encuadre y posición consistentes.",
          "Respaldo: transferencia, nombres y copia antes de formatear.",
        ],
        example: "Sesión de 90 minutos: 10 de prueba, 50 para cinco piezas, 15 para aperturas alternativas, 10 para B-roll y 5 para respaldo y notas.",
        practice: "Realiza una sesión de cinco guiones. Cronometra preparación, grabación y respaldo. Registra fallas y modifica el checklist antes de la siguiente sesión.",
        deliverable: "Cinco videos grabados, archivos organizados y protocolo mejorado.",
      },
    ],
    mission: {
      title: "Sesión cero a cinco",
      brief: "Construye tu set y completa una sesión de cinco piezas con calidad técnica y presencia consistente.",
      steps: [
        "Configura audio, luz, cámara, fondo y seguridad de archivos.",
        "Graba una prueba y revísala con auriculares.",
        "Ordena cinco guiones por energía y complejidad.",
        "Graba aperturas, cuerpos, cierres y B-roll necesario.",
        "Respalda, nombra y documenta notas de edición.",
      ],
      deliverable: "Set documentado, cinco piezas grabadas y checklist de sesión.",
    },
    checklist: [
      "La voz se entiende sin subir el volumen.",
      "La luz separa el rostro del fondo.",
      "El encuadre deja espacio para interfaz y subtítulos.",
      "La intención se siente natural y clara.",
      "Los archivos están nombrados y respaldados.",
    ],
    resources: [
      { title: "Checklist de set", type: "Guía", description: "Audio, luz, cámara, fondo, batería, almacenamiento y prueba técnica." },
      { title: "Plan de sesión", type: "Plantilla", description: "Orden de guiones, tomas alternativas, B-roll, utilería y notas." },
      { title: "Auditoría frente a cámara", type: "Plantilla", description: "Evalúa intención, mirada, ritmo, voz, postura y claridad." },
    ],
  },
  {
    number: "12",
    slug: "edicion",
    title: "Edición",
    phase: "Producción y plataformas",
    phaseNumber: "03",
    duration: "4 h 30 min",
    promise: "Editar con criterio para que cada corte, texto, sonido y visual mejore comprensión, ritmo y emoción.",
    summary: "Editar no es añadir efectos: es decidir qué debe permanecer y en qué orden. Aprenderás un flujo desde organización y corte de contenido hasta subtítulos, audio, color, exportación y control de calidad. El objetivo es crear piezas nativas y claras sin pasar horas puliendo detalles que la audiencia no percibe.",
    outcomes: [
      "Organizar material y construir un primer corte por significado.",
      "Controlar ritmo sin eliminar pausas humanas necesarias.",
      "Usar texto, B-roll, sonido y color con función editorial.",
      "Exportar y revisar piezas en distintos dispositivos.",
    ],
    lessons: [
      {
        number: "12.1",
        title: "Flujo de edición y primer corte",
        duration: "60 min",
        objective: "Pasar de archivos crudos a una estructura comprensible antes de decorar.",
        concept: "El primer corte resuelve contenido: selecciona la mejor toma, elimina errores, ordena ideas y confirma que la promesa se cumple. Organiza carpetas y versiones para poder regresar. No agregues animaciones mientras todavía dudas sobre qué debe decir la pieza.",
        framework: [
          "Ingesta: copiar, respaldar, nombrar y sincronizar.",
          "Selección: marcar tomas por claridad, intención y calidad técnica.",
          "Corte de contenido: ordenar idea, ejemplo, prueba y cierre.",
          "Corte fino: ajustar respiraciones, pausas y continuidad.",
        ],
        example: "Versión 01 contiene estructura limpia sin música ni texto. Solo cuando puede entenderse con la imagen principal pasas a reforzar con recursos.",
        practice: "Edita una pieza completa en dos pasadas separadas. En la primera decide contenido; en la segunda ajusta ritmo. Registra cuánto tiempo ahorras frente a mezclar tareas.",
        deliverable: "Primer corte aprobado y estructura de carpetas reutilizable.",
      },
      {
        number: "12.2",
        title: "Ritmo, cortes y retención",
        duration: "65 min",
        objective: "Mantener progreso perceptible sin convertir la pieza en ruido visual.",
        concept: "El ritmo nace de la densidad de ideas, la intención y la expectativa de formato. Corta cuando cambia la idea, la emoción o la información visual. Elimina demoras, no humanidad. Un cambio constante sin motivo puede reducir comprensión aunque aumente movimiento.",
        framework: [
          "Progreso: cada bloque responde o abre una pregunta relevante.",
          "Variación: alterna escala, visual o voz cuando cambia la función.",
          "Pausa: permite procesar, enfatizar o generar anticipación.",
          "Patrón roto: usa cambio fuerte solo en momentos estratégicos.",
        ],
        example: "En una explicación técnica, un acercamiento puede marcar la conclusión; un corte a pantalla demuestra; una pausa antes del resultado añade peso. No necesitas zoom cada dos segundos.",
        practice: "Edita dos versiones del mismo minuto: una agresiva y otra respirable. Pide a cinco personas explicar el contenido y calificar claridad, energía y confianza.",
        deliverable: "Guía de ritmo propia según formato y audiencia.",
      },
      {
        number: "12.3",
        title: "Subtítulos, B-roll, audio y color",
        duration: "70 min",
        objective: "Añadir capas que mejoren accesibilidad, demostración y coherencia visual.",
        concept: "Los subtítulos deben poder leerse y seguir la voz sin competir con el rostro. El B-roll prueba o contextualiza. La música sostiene emoción sin cubrir lenguaje. El color corrige consistencia antes de estilizar. Cada capa debe justificar su presencia.",
        framework: [
          "Texto: contraste, tamaño móvil, dos líneas y palabras clave limitadas.",
          "B-roll: demostrar, ubicar, comparar o descansar la vista.",
          "Audio: voz primero, ruido controlado y música debajo del mensaje.",
          "Color: exposición y piel consistentes antes de aplicar estilo.",
        ],
        example: "Cuando dices “el perfil estaba saturado”, muestra el antes; al explicar la solución, enseña la nueva jerarquía. El recurso reemplaza descripción innecesaria.",
        practice: "Añade capas a un primer corte y desactívalas una por una. Si la pieza conserva la misma comprensión y emoción, esa capa puede eliminarse.",
        deliverable: "Pieza final con subtítulos accesibles, mezcla básica y recursos funcionales.",
      },
      {
        number: "12.4",
        title: "Exportación, revisión y biblioteca",
        duration: "55 min",
        objective: "Evitar errores de formato, compresión, derechos y publicación.",
        concept: "La edición termina cuando la pieza funciona donde será consumida. Revisa en teléfono, con y sin sonido, brillo bajo y conexión normal. Verifica ortografía, zonas seguras, relación de aspecto, créditos, derechos musicales y miniatura. Conserva proyecto, maestro y versión publicada con nombres claros.",
        framework: [
          "Técnica: resolución, relación, cuadros, códec y nivel de audio.",
          "Editorial: promesa cumplida, datos, ortografía y CTA.",
          "Plataforma: zonas seguras, portada, duración y derechos.",
          "Archivo: proyecto, fuentes, maestro y exportación final.",
        ],
        example: "Antes de publicar un vertical, reproduce en el teléfono y verifica que subtítulos no queden detrás del nombre de usuario, descripción o botones laterales.",
        practice: "Crea un preset por plataforma y una lista de revisión de 20 puntos. Procesa tres piezas y registra cualquier error detectado después de exportar.",
        deliverable: "Presets documentados, checklist y biblioteca organizada.",
      },
    ],
    mission: {
      title: "De crudo a publicado",
      brief: "Edita una pieza completa con un proceso replicable y documenta una plantilla para futuras producciones.",
      steps: [
        "Organiza y respalda todo el material.",
        "Construye primer corte y corte fino por separado.",
        "Añade únicamente capas con función clara.",
        "Exporta con preset y revisa en teléfono.",
        "Archiva proyecto, maestro y versión publicada.",
      ],
      deliverable: "Video final, proyecto organizado y protocolo de edición.",
    },
    checklist: [
      "La pieza funciona antes de añadir efectos.",
      "El ritmo mejora comprensión.",
      "Los subtítulos son legibles en móvil.",
      "La voz domina la mezcla.",
      "La exportación respeta zonas seguras y derechos.",
    ],
    resources: [
      { title: "Flujo de edición", type: "Guía", description: "Ingesta, selección, corte, capas, mezcla, exportación y archivo." },
      { title: "Checklist de publicación", type: "Plantilla", description: "Veinte controles técnicos, editoriales, legales y de plataforma." },
      { title: "Biblioteca de proyectos", type: "Plantilla", description: "Convención para archivos, versiones, fuentes y maestros." },
    ],
  },
  {
    number: "13",
    slug: "instagram",
    title: "Instagram",
    phase: "Producción y plataformas",
    phaseNumber: "03",
    duration: "5 h",
    promise: "Convertir Instagram en un sistema de descubrimiento, confianza y conversación comercial, no en una vitrina de publicaciones aisladas.",
    summary: "Instagram combina varias superficies con comportamientos distintos: perfil, Feed, Reels, Stories, búsqueda y mensajes. Diseñarás un perfil que orienta, una mezcla de formatos con función, un sistema de conversación y una revisión de Insights. La estrategia prioriza contenido original, elegible y útil antes que trucos de alcance.",
    outcomes: [
      "Construir un perfil que comunica posicionamiento y siguiente paso.",
      "Asignar funciones distintas a Reels, carruseles y Stories.",
      "Crear señales de descubrimiento, relación y conversión.",
      "Ejecutar un sprint de 30 días con métricas y aprendizaje.",
    ],
    lessons: [
      {
        number: "13.1",
        title: "Perfil y recorrido de confianza",
        duration: "60 min",
        objective: "Hacer que una visita al perfil termine en comprensión y una acción clara.",
        concept: "El perfil responde en segundos: quién eres, para quién, qué valor entregas, qué prueba tienes y qué debe hacer la persona. Nombre, foto, biografía, enlace, fijados y destacados trabajan juntos. El objetivo no es contar toda tu historia, sino orientar la siguiente decisión.",
        framework: [
          "Nombre buscable: identidad y categoría comprensible.",
          "Biografía: audiencia, transformación, prueba o método y CTA.",
          "Fijados: punto de vista, proceso y caso.",
          "Destacados: inicio, servicios, prueba, preguntas y detrás de escena.",
        ],
        example: "Una persona llega por un Reel sobre mensajes confusos. Encuentra una bio que promete claridad, un fijado con diagnóstico, otro con método y un caso; después descarga una hoja específica.",
        practice: "Realiza una prueba de cinco segundos con cinco personas. Muéstrales el perfil y pregunta qué haces, para quién y qué podrían hacer después. Corrige las respuestas ambiguas.",
        deliverable: "Perfil reescrito, tres fijados planificados y destacados ordenados.",
      },
      {
        number: "13.2",
        title: "Reels, carruseles y Stories con función",
        duration: "75 min",
        objective: "Usar cada formato para una tarea específica dentro del sistema.",
        concept: "Reels favorece descubrimiento y demostración; carruseles organizan ideas que merecen guardarse; Stories construye frecuencia, contexto y respuesta directa. No repitas exactamente la misma pieza. Conserva la idea núcleo y adapta entrada, profundidad, interacción y CTA.",
        framework: [
          "Reels: una idea, entrada rápida, demostración y continuidad.",
          "Carrusel: promesa, secuencia visual, ejemplo y resumen accionable.",
          "Stories: escena, opinión, participación y conversación.",
          "Sistema: cada formato conduce a otro activo o relación.",
        ],
        example: "Reel diagnostica un error de bio; carrusel entrega plantilla; Stories muestra una auditoría anónima y pregunta quién quiere revisar la suya; el destacado conserva respuestas frecuentes.",
        practice: "Toma una idea y crea un Reel, un carrusel de ocho láminas y una secuencia de cinco Stories. Diseña cómo se conectan durante una semana.",
        deliverable: "Campaña nativa de una semana en tres formatos.",
      },
      {
        number: "13.3",
        title: "Descubrimiento, elegibilidad y comunidad",
        duration: "70 min",
        objective: "Aumentar oportunidades de recomendación sin sacrificar originalidad ni confianza.",
        concept: "Instagram puede recomendar contenido de cuentas públicas a personas que no siguen la cuenta, siempre que sea elegible. La distribución depende de personalización, información de la pieza, respuesta observada y contexto. Revisa Estado de la cuenta, prioriza contenido original y crea conversaciones reales; comprar interacción o copiar contenido daña señal y credibilidad.",
        framework: [
          "Elegibilidad: estado de cuenta y cumplimiento de recomendaciones.",
          "Claridad temática: texto, audio, visual y contexto coherentes.",
          "Valor compartible: utilidad o emoción que alguien quiere enviar.",
          "Comunidad: respuestas que profundizan relación y generan investigación.",
        ],
        example: "Un Reel original explica un problema con un ejemplo propio, responde preguntas en comentarios y convierte las mejores en nuevas piezas. El crecimiento nace del ciclo de valor y conversación.",
        practice: "Revisa Estado de la cuenta, originalidad y fuentes de tus últimas 20 piezas. Responde 30 conversaciones con intención de aprender, no de dejar emojis genéricos.",
        deliverable: "Auditoría de elegibilidad y protocolo semanal de comunidad.",
      },
      {
        number: "13.4",
        title: "Insights y sprint de 30 días",
        duration: "75 min",
        objective: "Tomar decisiones editoriales usando tendencias por formato, serie y objetivo.",
        concept: "Alcance sin contexto no es estrategia. Revisa fuentes de descubrimiento, tiempo de visualización, interacción de calidad, visitas al perfil, seguidores adecuados y conversaciones. Compara piezas con funciones similares y observa series durante varias entregas. Documenta qué repetirás y por qué.",
        framework: [
          "Descubrimiento: alcance a no seguidores y entradas al perfil.",
          "Consumo: reproducciones, tiempo visto y finalización.",
          "Valor: guardados, compartidos, respuestas y mensajes.",
          "Negocio: clics, solicitudes, conversaciones y ventas atribuidas.",
        ],
        example: "Una serie puede tener menos likes y más mensajes calificados. Si su objetivo es conversación, no debe eliminarse por comparación con un Reel de entretenimiento.",
        practice: "Planifica 30 días con tres series, dos formatos principales y una campaña. Define línea base, métrica primaria y reunión de revisión semanal.",
        deliverable: "Sprint de Instagram de 30 días y tablero de Insights.",
      },
    ],
    mission: {
      title: "Instagram como sistema",
      brief: "Alinea perfil, contenido, conversación y medición en una ruta completa de descubrimiento a acción.",
      steps: [
        "Optimiza nombre, bio, enlace, fijados y destacados.",
        "Crea una campaña en Reel, carrusel y Stories.",
        "Audita elegibilidad, originalidad y atribución.",
        "Establece un bloque semanal de comunidad.",
        "Ejecuta y revisa un sprint de 30 días.",
      ],
      deliverable: "Perfil optimizado, campaña multiformato y tablero mensual.",
    },
    checklist: [
      "El perfil explica para quién y qué transformación ofrezco.",
      "Cada formato cumple una función distinta.",
      "El contenido añade valor original.",
      "Reviso Estado de la cuenta y derechos.",
      "Mido conversaciones y negocio además de alcance.",
    ],
    resources: [
      { title: "Auditoría de perfil", type: "Plantilla", description: "Nombre, bio, enlace, fijados, destacados, prueba y ruta de acción." },
      { title: "Tablero de Insights", type: "Tablero", description: "Descubrimiento, consumo, valor, perfil, conversación y negocio por serie." },
      { title: "Best Practices de Instagram", type: "Referencia oficial", description: "Centro educativo de Instagram para creación, engagement, reach, monetización y normas.", href: "https://about.fb.com/news/2024/10/best-practices-education-hub-creators-instagram/" },
      { title: "Elegibilidad de recomendaciones", type: "Referencia oficial", description: "Cómo revisar si una cuenta y sus contenidos pueden recomendarse.", href: "https://www.facebook.com/help/instagram/653964212890722" },
    ],
  },
  {
    number: "14",
    slug: "tiktok",
    title: "TikTok",
    phase: "Producción y plataformas",
    phaseNumber: "03",
    duration: "4 h 45 min",
    promise: "Crear contenido nativo, encontrable y serializado que TikTok pueda conectar con la audiencia correcta.",
    summary: "TikTok es un sistema de descubrimiento basado en intereses y comportamiento. La estrategia combina lenguaje nativo, claridad temática, retención, búsqueda, series y comunidad. Aprenderás a investigar señales culturales sin copiar tendencias, diseñar contenido original y ejecutar un sprint de 21 días con hipótesis claras.",
    outcomes: [
      "Traducir tu posicionamiento al lenguaje y ritmo de TikTok.",
      "Diseñar videos para elección, consumo y respuesta.",
      "Usar búsqueda, comentarios y series como motores de ideas.",
      "Ejecutar un sprint de 21 días y decidir qué formatos escalar.",
    ],
    lessons: [
      {
        number: "14.1",
        title: "Lenguaje nativo sin perder identidad",
        duration: "60 min",
        objective: "Adaptar entrega, encuadre y contexto sin imitar personajes ajenos.",
        concept: "Nativo significa comprensible dentro del entorno: entrada directa, encuadre cercano, contexto rápido, demostración y participación. No exige bailar ni usar cada tendencia. Observa patrones de comunicación y reconstruye solo los que sirven a tu punto de vista.",
        framework: [
          "Convención: forma familiar que reduce esfuerzo de comprensión.",
          "Aporte: experiencia, análisis o demostración que te pertenece.",
          "Velocidad: entra en contexto antes de pedir paciencia.",
          "Humanidad: conserva voz, opiniones y límites propios.",
        ],
        example: "En vez de copiar un audio, usa el formato “tres señales de que…” para diagnosticar un problema que ves en clientes y añade una demostración real.",
        practice: "Analiza 30 videos de tu nicho por apertura, plano, duración, estructura y comentarios. Identifica cinco convenciones que puedes adaptar y cinco que no corresponden a tu marca.",
        deliverable: "Mapa de lenguaje nativo y cinco formatos propios.",
      },
      {
        number: "14.2",
        title: "Para Ti, retención y satisfacción",
        duration: "70 min",
        objective: "Diseñar señales fuertes de relevancia sin reducir el contenido a trucos.",
        concept: "El feed Para Ti es personalizado y aprende de interacciones, consumo, búsqueda, cuentas y contenido. Una finalización puede ser una señal fuerte, pero debe interpretarse junto con compartidos, comentarios, seguimiento y repetición. El video debe declarar tema rápido, cumplir promesa y entregar progreso visible.",
        framework: [
          "Selección: primer cuadro, frase y contexto temático.",
          "Retención: pregunta abierta, progreso y densidad adecuada.",
          "Satisfacción: utilidad, emoción, conversación y retorno.",
          "Continuidad: serie, perfil y siguiente pieza relacionada.",
        ],
        example: "Serie “Te audito la bio”: abre mostrando el síntoma, explica una decisión, presenta el cambio y cierra invitando a ver el caso anterior o responder con otra bio.",
        practice: "Crea tres versiones de apertura para cinco temas. Publica variaciones controladas y compara retención inicial, tiempo medio, comentarios y visitas al perfil.",
        deliverable: "Matriz de aperturas y resultados por señal.",
      },
      {
        number: "14.3",
        title: "Búsqueda, series y comunidad",
        duration: "65 min",
        objective: "Construir descubrimiento acumulativo alrededor de preguntas específicas.",
        concept: "TikTok también funciona como buscador. La frase hablada, texto en pantalla, caption y contenido deben coincidir con una intención real. Las series agrupan temas y enseñan al usuario qué esperar. Los comentarios son investigación: revelan confusión, ejemplos y próximos episodios.",
        framework: [
          "Intención: pregunta exacta que la persona quiere resolver.",
          "Señales semánticas: voz, texto y caption alineados.",
          "Serie: promesa repetible y numeración visible.",
          "Comunidad: responder, citar, convertir comentarios en contenido.",
        ],
        example: "Pregunta: “cómo poner precio a una asesoría”. El video pronuncia la frase, la muestra en pantalla, responde con tres variables y enlaza la parte dos sobre alcance.",
        practice: "Recopila 30 búsquedas sugeridas y preguntas. Agrúpalas en tres series de diez episodios y escribe una respuesta central para cada una.",
        deliverable: "Mapa de búsqueda y tres series de diez episodios.",
      },
      {
        number: "14.4",
        title: "Sprint de publicación de 21 días",
        duration: "70 min",
        objective: "Obtener suficiente evidencia para identificar temas, formatos y series prometedoras.",
        concept: "Un sprint no busca viralidad diaria. Busca volumen suficiente para aprender sin bajar estándares. Combina temas probados, formatos experimentales y respuestas a comunidad. Revisa bloques de siete días, conserva ganadores por calidad de audiencia y evita borrar piezas solo por bajo arranque.",
        framework: [
          "70% núcleo: series alineadas con posicionamiento.",
          "20% prueba: nuevos formatos, duraciones o empaques.",
          "10% respuesta: conversación, actualidad y colaboración.",
          "Revisión: tema, formato, señal, audiencia y siguiente iteración.",
        ],
        example: "Durante 21 días publicas una serie de diagnóstico, otra de demostración y respuestas a preguntas. Al final no eliges el video con más vistas, sino la combinación que trajo mejores visitas y conversaciones.",
        practice: "Planifica 21 piezas, graba por lotes y revisa cada siete días. Selecciona tres formatos para iterar durante el siguiente mes.",
        deliverable: "Sprint de 21 días, tablero de señales y plan de continuidad.",
      },
    ],
    mission: {
      title: "Reto TikTok 21",
      brief: "Publica una secuencia estratégica suficiente para identificar lenguaje, temas y formatos con potencial real.",
      steps: [
        "Investiga convenciones, búsquedas y preguntas del nicho.",
        "Diseña tres series con promesa y estructura.",
        "Prepara 21 briefs y graba por lotes.",
        "Publica, responde y documenta señales durante tres semanas.",
        "Elige ganadores por audiencia y acción, no solo por vistas.",
      ],
      deliverable: "Veintiuna piezas, tres series validadas y mapa de aprendizaje.",
    },
    checklist: [
      "El contenido se siente nativo sin perder mi voz.",
      "Tema y promesa aparecen rápidamente.",
      "Las señales semánticas coinciden con la intención de búsqueda.",
      "Convierto comentarios en investigación y contenido.",
      "Evalúo bloques de piezas, no un solo resultado.",
    ],
    resources: [
      { title: "Mapa de formatos nativos", type: "Plantilla", description: "Convención, adaptación propia, tema, gancho, prueba y CTA." },
      { title: "Reto TikTok 21", type: "Tablero", description: "Producción, publicación, señales, comentarios y decisión por pieza." },
      { title: "Cómo TikTok recomienda contenido", type: "Referencia oficial", description: "Factores de interacción, información y contexto en los feeds de recomendación.", href: "https://support.tiktok.com/en/using-tiktok/exploring-videos/how-tiktok-recommends-content" },
      { title: "Making your feed For You", type: "Referencia oficial", description: "Guía de TikTok sobre calidad, frescura, interacción y personalización.", href: "https://www.tiktok.com/safety/en/making-your-feed-for-you" },
    ],
  },
  {
    number: "15",
    slug: "youtube",
    title: "YouTube",
    phase: "Producción y plataformas",
    phaseNumber: "03",
    duration: "5 h 30 min",
    promise: "Construir un canal que gane elección, retenga atención y acumule autoridad mediante contenido encontrable y recomendable.",
    summary: "YouTube combina búsqueda, inicio, sugeridos, suscripciones y Shorts. El sistema intenta encontrar videos relevantes para cada espectador y maximizar satisfacción a largo plazo. Diseñarás estrategia de canal, empaque, retención, biblioteca y análisis para producir activos que sigan trabajando después de publicarse.",
    outcomes: [
      "Definir la promesa del canal y una arquitectura de series.",
      "Crear títulos y miniaturas que consiguen clics calificados.",
      "Diseñar videos largos con progreso y satisfacción.",
      "Interpretar búsqueda, recomendaciones y Analytics por intención.",
    ],
    lessons: [
      {
        number: "15.1",
        title: "Estrategia de canal y biblioteca",
        duration: "70 min",
        objective: "Construir una promesa clara y un catálogo que facilite ver la siguiente pieza.",
        concept: "Un canal fuerte responde qué audiencia, qué transformación y qué tipo de experiencia ofrece repetidamente. Piensa en biblioteca, no en publicaciones aisladas. Las series conectan preguntas, niveles y formatos; las listas y pantallas finales ayudan a continuar.",
        framework: [
          "Promesa de canal: por qué una persona adecuada debería suscribirse.",
          "Series: preguntas recurrentes con formato reconocible.",
          "Rutas: orden de contenido para principiante, intermedio y comprador.",
          "Continuidad: siguiente video definido antes de publicar el actual.",
        ],
        example: "Canal para consultores: claridad de oferta, mensajes que venden, casos auditados y sistemas de contenido. Cada video dirige a una pieza más profunda o al siguiente problema lógico.",
        practice: "Audita diez canales comparables. Diseña una promesa, cuatro series y tres rutas de reproducción de cinco videos.",
        deliverable: "Arquitectura de canal con series, rutas y próximos 20 títulos.",
      },
      {
        number: "15.2",
        title: "Packaging: idea, título y miniatura",
        duration: "75 min",
        objective: "Aumentar elección representando con precisión el valor del video.",
        concept: "Título y miniatura forman una promesa conjunta. El título puede aportar contexto, resultado o pregunta; la miniatura debe comunicar una idea visual simple, no repetir cada palabra. Diseña el empaque antes de grabar para confirmar que la idea tiene tensión y audiencia.",
        framework: [
          "Idea: tema con demanda, tensión y enfoque específico.",
          "Título: claridad, relevancia y brecha de información.",
          "Miniatura: sujeto, contraste, emoción o prueba visible.",
          "Cumplimiento: los primeros 30 segundos entregan lo prometido.",
        ],
        example: "Título: “Por qué tu oferta necesita una sola promesa”. Miniatura: dos propuestas, una saturada y una clara, con la frase “¿Cuál recuerdas?”. No hace falta repetir el título.",
        practice: "Diseña diez combinaciones de título y miniatura para tres ideas. Reduce cada miniatura a una lectura móvil y prueba comprensión sin explicar el video.",
        deliverable: "Treinta conceptos de packaging y tres seleccionados.",
      },
      {
        number: "15.3",
        title: "Retención y satisfacción en video largo",
        duration: "85 min",
        objective: "Mantener progreso desde la promesa inicial hasta una conclusión útil.",
        concept: "YouTube no requiere cortes constantes; requiere que el espectador reciba valor y quiera continuar. Abre confirmando promesa, establece mapa, avanza por capítulos y combina explicación con evidencia. Revisa caídas como preguntas: ¿la entrada fue lenta?, ¿el título prometió otra cosa?, ¿faltó ejemplo?, ¿la sección pudo ser más corta?",
        framework: [
          "Confirmación: muestra que el video correcto comenzó.",
          "Progreso: capítulos con preguntas y recompensas claras.",
          "Variación: ejemplos, gráficos, historias y demostraciones.",
          "Satisfacción: cierre completo y siguiente video relevante.",
        ],
        example: "Un tutorial anuncia tres decisiones, muestra el resultado final y avanza una por una. Cada capítulo termina aplicando la decisión a un caso real.",
        practice: "Crea escaleta y graba un video de 12 a 20 minutos. Después de publicar, revisa retención por momentos y anota hipótesis, no culpas.",
        deliverable: "Video largo completo y mapa de retención comentado.",
      },
      {
        number: "15.4",
        title: "Búsqueda, recomendaciones y Analytics",
        duration: "80 min",
        objective: "Interpretar cómo se descubre el contenido y qué decisión editorial corresponde.",
        concept: "En búsqueda importan relevancia, engagement y calidad; en inicio y sugeridos pesan personalización y rendimiento cuando el video se ofrece. No todo tema tiene el mismo interés o competencia. Observa fuente de tráfico, impresiones, clic, retención, espectadores nuevos y recurrentes, y videos que conducen a otros.",
        framework: [
          "Búsqueda: intención, coincidencia semántica, calidad y satisfacción.",
          "Inicio: respuesta de espectadores adecuados cuando se muestra.",
          "Sugeridos: relación temática y probabilidad de ver a continuación.",
          "Biblioteca: retorno, sesiones y profundidad de consumo.",
        ],
        example: "Un video con pocas impresiones y alto clic puede tratar un tema pequeño; uno con muchas impresiones y bajo clic necesita empaque; uno con buen clic y caída rápida incumple promesa.",
        practice: "Analiza diez videos por fuente de tráfico y embudo impresión–elección–consumo–continuidad. Define una mejora principal para cada uno.",
        deliverable: "Tablero de Analytics y plan de próximos diez videos.",
      },
    ],
    mission: {
      title: "Canal con sistema",
      brief: "Diseña la arquitectura y publica un video insignia con empaque, retención y continuidad planificados.",
      steps: [
        "Define promesa, series y rutas del canal.",
        "Selecciona una idea y diseña packaging antes del guion.",
        "Crea escaleta, graba y edita el video largo.",
        "Conecta descripción, capítulos, pantalla final y siguiente video.",
        "Revisa Analytics y documenta una iteración.",
      ],
      deliverable: "Arquitectura del canal, video insignia y tablero de diagnóstico.",
    },
    checklist: [
      "El canal tiene una promesa comprensible.",
      "Título y miniatura cuentan una sola historia.",
      "El inicio confirma rápidamente la promesa.",
      "Cada capítulo produce progreso visible.",
      "El video conduce a otra pieza relevante.",
    ],
    resources: [
      { title: "Arquitectura de canal", type: "Plantilla", description: "Promesa, series, rutas, biblioteca y continuidad." },
      { title: "Laboratorio de packaging", type: "Plantilla", description: "Idea, audiencia, título, miniatura, prueba y cumplimiento." },
      { title: "Rendimiento y descubrimiento", type: "Referencia oficial", description: "Preguntas frecuentes de YouTube sobre promoción, inicio, sugeridos y búsqueda.", href: "https://support.google.com/youtube/answer/141805" },
      { title: "Sistema de recomendaciones", type: "Referencia oficial", description: "Objetivos, personalización y señales de rendimiento explicados por YouTube.", href: "https://support.google.com/youtube/answer/16533387" },
    ],
  },
];
