import type { CourseModuleContent } from "./types";

export const phaseFourModules: CourseModuleContent[] = [
  {
    number: "16",
    slug: "inteligencia-artificial",
    title: "Inteligencia Artificial",
    phase: "Negocio y escala",
    phaseNumber: "04",
    duration: "5 h",
    promise: "Usar inteligencia artificial como copiloto de investigación, creación y operación sin perder criterio, voz ni control de calidad.",
    summary: "La IA acelera tareas, pero también puede multiplicar ideas genéricas y errores. Este módulo enseña un sistema independiente de herramientas: definir trabajo, aportar contexto, pedir una salida verificable, evaluar, corregir y documentar. Construirás flujos para investigación, ideación, guiones, reutilización y análisis con controles de privacidad y originalidad.",
    outcomes: [
      "Decidir qué tareas conviene delegar, aumentar o mantener humanas.",
      "Escribir instrucciones con contexto, criterios y ejemplos.",
      "Crear flujos de IA para investigación, contenido y reutilización.",
      "Implementar revisión de hechos, voz, riesgo y calidad antes de publicar.",
    ],
    lessons: [
      {
        number: "16.1",
        title: "El creador aumentado, no reemplazado",
        duration: "60 min",
        objective: "Asignar IA según riesgo, repetición y necesidad de juicio.",
        concept: "La IA es útil para expandir opciones, organizar información, transformar formatos y revisar patrones. Es menos confiable cuando debe inventar hechos, interpretar contextos sensibles, tomar decisiones reputacionales o reemplazar experiencia que no le proporcionaste. Tu ventaja no es generar más texto; es combinar criterio, datos propios, historias y una voz que el modelo no puede conocer sin contexto.",
        framework: [
          "Automatizar: tareas repetibles, reversibles y fáciles de verificar.",
          "Aumentar: investigación, ideación y análisis donde el humano decide.",
          "Reservar: estrategia, promesas, relaciones y decisiones de alto riesgo.",
          "Registrar: fuente, versión, criterio y responsable de aprobación.",
        ],
        example: "Puedes pedir 20 ángulos para una pregunta real y elegir tres con evidencia. No deberías publicar una estadística generada sin confirmar la fuente ni permitir que redacte un caso de cliente que nunca ocurrió.",
        practice: "Lista 30 tareas de tu proceso. Califica repetición, riesgo, facilidad de verificación y valor de tu juicio. Clasifica cada una en automatizar, aumentar o reservar.",
        deliverable: "Mapa de uso responsable de IA para tu negocio.",
      },
      {
        number: "16.2",
        title: "Instrucciones que producen trabajo útil",
        duration: "75 min",
        objective: "Diseñar prompts como briefs profesionales con criterios de evaluación.",
        concept: "Un prompt sólido define objetivo, contexto, insumos, restricciones, formato y criterio de éxito. Los ejemplos muestran el estándar mejor que una lista interminable de adjetivos. Trabaja en etapas: primero estrategia, luego opciones, selección, desarrollo y revisión. Conserva la conversación crítica en lugar de aceptar la primera salida.",
        framework: [
          "Objetivo: qué decisión o artefacto necesitas.",
          "Contexto: audiencia, oferta, voz, canal y evidencia disponible.",
          "Restricciones: qué evitar, longitud, fuentes y límites.",
          "Criterio: cómo evaluar claridad, originalidad, precisión y utilidad.",
        ],
        example: "En vez de “hazme ideas virales”, entrega tres citas de clientes, posicionamiento, pilares y ejemplos de voz. Pide diez ángulos, exige que cada uno indique problema, promesa y evidencia necesaria, y rechaza los que dependan de exageración.",
        practice: "Toma una tarea real y crea un prompt en cinco bloques. Ejecuta, evalúa con una rúbrica y reescribe solo la parte de instrucción que falló.",
        deliverable: "Cinco prompts maestros con rúbrica y ejemplo aprobado.",
      },
      {
        number: "16.3",
        title: "Flujos para investigar y crear",
        duration: "85 min",
        objective: "Convertir materiales propios en ideas, briefs y borradores trazables.",
        concept: "El mejor flujo comienza con insumos reales: entrevistas, notas, transcripciones, métricas y documentos de marca. Pide extraer patrones antes de generar piezas. Separa hechos de inferencias, conserva citas y verifica cualquier dato externo. Después usa el modelo para proponer ángulos, estructurar y criticar; la decisión editorial sigue siendo humana.",
        framework: [
          "Ingesta: limpiar y etiquetar información autorizada.",
          "Extracción: preguntas, patrones, tensiones, citas y vacíos.",
          "Creación: ángulos, briefs, estructuras y versiones.",
          "Validación: fuente, voz, promesa, riesgo y aporte original.",
        ],
        example: "Subes una transcripción de entrevista, pides extraer citas por objeción, eliges una tensión y solicitas tres briefs. Después verificas citas, añades experiencia y escribes el guion final.",
        practice: "Construye un flujo con cinco entrevistas o una hora de notas. Produce un mapa de patrones, diez briefs y dos guiones; registra qué fue generado y qué cambiaste.",
        deliverable: "Pipeline documentado de investigación a guion con trazabilidad.",
      },
      {
        number: "16.4",
        title: "Reutilización, QA y biblioteca de conocimiento",
        duration: "80 min",
        objective: "Escalar producción preservando contexto, consistencia y revisión humana.",
        concept: "Reutilizar con IA requiere una fuente maestra y reglas por formato. La herramienta puede extraer clips, resumir, adaptar y proponer CTA, pero cada pieza debe ser completa y nativa. Una lista de calidad revisa exactitud, voz, repetición, derechos, privacidad y promesa. Guarda prompts, fuentes y correcciones para que el sistema aprenda de tus decisiones.",
        framework: [
          "Fuente maestra: contenido aprobado y versión definitiva.",
          "Transformación: objetivo, plataforma y contexto de cada derivado.",
          "QA: hechos, voz, originalidad, riesgos y accesibilidad.",
          "Memoria operativa: biblioteca de ejemplos, errores y decisiones.",
        ],
        example: "Una clase de 30 minutos puede generar clips, carrusel y correo. Antes de publicar, cada activo recibe una entrada nativa, ejemplo suficiente, CTA propio y revisión contra la fuente.",
        practice: "Reutiliza una pieza larga en siete activos. Compara con la fuente, elimina invenciones y registra las correcciones que repetirás como instrucciones futuras.",
        deliverable: "Sistema de reutilización, checklist QA y biblioteca inicial.",
      },
    ],
    mission: {
      title: "Sistema operativo con IA",
      brief: "Crea un flujo completo que parte de datos propios y termina en contenido revisado, trazable y listo para producción.",
      steps: [
        "Clasifica tareas en automatizar, aumentar y reservar.",
        "Construye cinco prompts con criterios y ejemplos.",
        "Procesa investigación real y extrae patrones verificables.",
        "Genera un activo maestro y siete derivados nativos.",
        "Aplica QA y documenta cada corrección importante.",
      ],
      deliverable: "Mapa de tareas, biblioteca de prompts y pipeline de contenido con QA.",
    },
    checklist: [
      "No comparto información sensible sin autorización.",
      "Separo hechos, inferencias y propuestas.",
      "Cada afirmación externa tiene fuente verificada.",
      "La salida conserva mi punto de vista y ejemplos.",
      "Una persona identificada aprueba antes de publicar.",
    ],
    resources: [
      { title: "Mapa de tareas con IA", type: "Plantilla", description: "Riesgo, repetición, reversibilidad, verificación y nivel de intervención humana." },
      { title: "Constructor de prompts", type: "Plantilla", description: "Objetivo, contexto, insumos, restricciones, formato, ejemplo y rúbrica." },
      { title: "QA de contenido asistido", type: "Guía", description: "Revisión de fuentes, voz, privacidad, derechos, originalidad y promesa." },
      { title: "Guías de OpenAI", type: "Referencia oficial", description: "Documentación oficial para texto, archivos, herramientas y prácticas de implementación.", href: "https://platform.openai.com/docs/guides" },
    ],
  },
  {
    number: "17",
    slug: "automatizacion",
    title: "Automatización",
    phase: "Negocio y escala",
    phaseNumber: "04",
    duration: "5 h",
    promise: "Diseñar procesos que muevan información y tareas automáticamente sin crear una maquinaria frágil o impersonal.",
    summary: "Automatizar no significa conectar muchas herramientas. Significa definir un proceso estable, identificar disparadores y decisiones, reducir trabajo repetitivo y conservar puntos humanos críticos. Mapearás contenido, leads, seguimiento y reportes; después crearás controles para errores, duplicados, permisos y excepciones.",
    outcomes: [
      "Documentar procesos antes de automatizarlos.",
      "Diseñar flujos con disparadores, acciones, datos y responsables.",
      "Automatizar captura, nutrición y operaciones editoriales con criterio.",
      "Implementar monitoreo, registro de fallas y rutas manuales.",
    ],
    lessons: [
      {
        number: "17.1",
        title: "Primero proceso, después herramienta",
        duration: "65 min",
        objective: "Eliminar, simplificar y estandarizar antes de conectar sistemas.",
        concept: "Automatizar un proceso confuso produce errores más rápido. Observa el flujo actual, identifica objetivo, entradas, decisiones, responsables y salida. Elimina pasos sin valor, reduce variantes y define condiciones de excepción. Solo entonces decide qué parte merece automatización.",
        framework: [
          "Eliminar: pasos que no cambian resultado ni reducen riesgo.",
          "Simplificar: menos campos, aprobaciones y movimientos.",
          "Estandarizar: nombres, estados, plantillas y criterios.",
          "Automatizar: tareas repetibles con regla y salida verificable.",
        ],
        example: "Antes de automatizar el calendario, define qué significa idea, aprobada, guion, grabada, editada y publicada; quién cambia cada estado y qué información mínima necesita.",
        practice: "Graba pantalla o documenta un proceso mientras lo ejecutas. Cuenta pasos, tiempo, errores y esperas. Rediseña una versión 30% más simple.",
        deliverable: "Mapa antes/después de un proceso prioritario.",
      },
      {
        number: "17.2",
        title: "Arquitectura de un flujo confiable",
        duration: "75 min",
        objective: "Definir cómo se mueve un dato desde el disparador hasta una salida aprobada.",
        concept: "Todo flujo tiene disparador, condiciones, acciones, datos, destino y dueño. Añade identificadores para evitar duplicados, validación antes de enviar y registro de cada ejecución. Las automatizaciones deben detenerse de forma segura cuando falta información.",
        framework: [
          "Trigger: evento específico que inicia el flujo.",
          "Filtro: condiciones que autorizan o detienen.",
          "Acciones: pasos ordenados y datos que cada uno necesita.",
          "Control: log, alerta, reintento y responsable de excepción.",
        ],
        example: "Formulario recibido → validar consentimiento y correo → crear contacto con ID → etiquetar interés → enviar recurso → registrar entrega → alertar si el envío falla.",
        practice: "Dibuja un flujo con casos feliz, incompleto, duplicado y error. Define qué ve el usuario y quién recibe la alerta en cada caso.",
        deliverable: "Especificación de automatización con rutas y controles.",
      },
      {
        number: "17.3",
        title: "Contenido, leads y seguimiento",
        duration: "80 min",
        objective: "Aplicar automatización a operaciones reales sin perder personalización importante.",
        concept: "En contenido puedes mover estados, generar tareas, programar recordatorios y consolidar métricas. En leads puedes capturar consentimiento, entregar recursos, segmentar por comportamiento y avisar a una persona cuando existe intención. No automatices conversaciones sensibles ni finjas atención humana.",
        framework: [
          "Editorial: idea, brief, producción, aprobación, publicación y archivo.",
          "Captura: fuente, consentimiento, interés y entrega prometida.",
          "Nutrición: secuencia útil según necesidad, no bombardeo genérico.",
          "Handoff: condición que transfiere a una conversación humana.",
        ],
        example: "Una respuesta con palabra clave entrega una guía, etiqueta el problema y pregunta si quiere recibir una auditoría. Solo una respuesta afirmativa crea tarea comercial humana.",
        practice: "Diseña un flujo editorial y uno de leads. Para cada mensaje automatizado, declara la expectativa, opción de salida y responsable.",
        deliverable: "Dos flujos implementables con mensajes y handoff humano.",
      },
      {
        number: "17.4",
        title: "Mantenimiento, seguridad y deuda operativa",
        duration: "60 min",
        objective: "Evitar que una automatización abandonada se convierta en riesgo de reputación o datos.",
        concept: "Los flujos fallan porque cambian campos, permisos, APIs, responsables o reglas. Cada automatización necesita dueño, documentación, prueba periódica y plan de apagado. Recoge solo datos necesarios, limita accesos y elimina información según política.",
        framework: [
          "Propiedad: responsable, fecha de revisión y propósito.",
          "Observabilidad: log, métricas, alertas y muestra de salidas.",
          "Seguridad: mínimos datos, permisos y consentimiento.",
          "Retiro: condición para pausar, corregir o eliminar el flujo.",
        ],
        example: "Una secuencia trimestral de prueba usa un contacto interno, verifica enlaces y etiquetas, revisa bajas y confirma que el responsable sigue activo.",
        practice: "Crea un inventario de automatizaciones. Puntúa impacto y riesgo; asigna dueño, revisión, alerta y procedimiento manual a cada una.",
        deliverable: "Registro de automatizaciones y protocolo de mantenimiento.",
      },
    ],
    mission: {
      title: "Automatización con barandas",
      brief: "Diseña dos flujos que ahorren tiempo, protejan datos y sepan cuándo pedir intervención humana.",
      steps: [
        "Mapea y simplifica un proceso editorial y uno comercial.",
        "Define disparadores, filtros, acciones y datos.",
        "Añade rutas para faltantes, duplicados y fallas.",
        "Escribe mensajes transparentes y handoff humano.",
        "Asigna dueño, revisión y plan de apagado.",
      ],
      deliverable: "Especificación completa de dos automatizaciones y registro de mantenimiento.",
    },
    checklist: [
      "El proceso funciona manualmente antes de automatizarlo.",
      "Cada flujo tiene un dueño y una razón medible.",
      "Los duplicados y datos faltantes tienen tratamiento.",
      "La persona sabe cuándo interactúa con un sistema automático.",
      "Existe una ruta manual y un plan de apagado.",
    ],
    resources: [
      { title: "Mapa de procesos", type: "Plantilla", description: "Objetivo, entrada, pasos, decisiones, dueño, salida y oportunidades de simplificación." },
      { title: "Especificación de flujo", type: "Plantilla", description: "Trigger, filtros, datos, acciones, errores, alertas y handoff." },
      { title: "Registro de automatizaciones", type: "Tablero", description: "Estado, responsable, impacto, riesgo, revisión y procedimiento manual." },
    ],
  },
  {
    number: "18",
    slug: "conversion",
    title: "Conversión",
    phase: "Negocio y escala",
    phaseNumber: "04",
    duration: "5 h 15 min",
    promise: "Construir una ruta clara desde el descubrimiento hasta la compra y mejorarla con evidencia, no presión.",
    summary: "Conversión es ayudar a avanzar a la persona adecuada. Diseñarás un recorrido de problema, confianza, oferta y decisión; una página que responde preguntas; secuencias de correo o mensajes; y un tablero para detectar dónde se pierde claridad. El foco es mejorar ajuste y reducir incertidumbre, no exprimir cada visita.",
    outcomes: [
      "Mapear el recorrido desde contenido hasta resultado del cliente.",
      "Diseñar una oferta con alcance, mecanismo y prueba comprensibles.",
      "Escribir página, secuencia y conversación de venta.",
      "Medir etapas y ejecutar experimentos de optimización.",
    ],
    lessons: [
      {
        number: "18.1",
        title: "El embudo como recorrido de decisiones",
        duration: "65 min",
        objective: "Definir qué necesita comprender y creer la persona en cada etapa.",
        concept: "Un embudo no es solo una secuencia técnica. Es una serie de decisiones: reconocer un problema, priorizarlo, confiar en un enfoque, evaluar una oferta y comprometer recursos. Cada activo debe resolver la duda principal de su etapa y conducir al siguiente paso con continuidad.",
        framework: [
          "Descubrimiento: “esto describe una situación que vivo”.",
          "Comprensión: “ahora entiendo por qué ocurre y qué cambia”.",
          "Confianza: “este método y esta persona parecen adecuados”.",
          "Decisión: “comprendo alcance, riesgo, precio y siguiente paso”.",
        ],
        example: "Un Reel diagnostica, una guía permite autoevaluarse, una secuencia enseña el método, un caso aporta prueba y una llamada confirma ajuste. Cada activo tiene una pregunta distinta.",
        practice: "Dibuja tu recorrido actual desde primera impresión hasta entrega. Marca dudas, activos, responsables, métricas y saltos donde exiges demasiado pronto.",
        deliverable: "Mapa de conversión con preguntas y activos por etapa.",
      },
      {
        number: "18.2",
        title: "Oferta y página que facilitan decidir",
        duration: "80 min",
        objective: "Presentar transformación, mecanismo, alcance, evidencia y ajuste de forma completa.",
        concept: "La página no debe impresionar antes de explicar. Comienza por la situación y resultado, muestra para quién, mecanismo, entregables, proceso, prueba, objeciones y CTA. Incluye para quién no es y qué esfuerzo requiere. La claridad filtra mejor que la presión.",
        framework: [
          "Promesa: resultado y condición sin garantía engañosa.",
          "Mecanismo: cómo el proceso produce avance.",
          "Alcance: incluye, no incluye, tiempo y responsabilidades.",
          "Prueba y riesgo: casos, preguntas, políticas y expectativas.",
        ],
        example: "En lugar de “transforma tu vida”, explica: “En cuatro semanas saldrás con posicionamiento, oferta y doce guiones; necesitas dos horas semanales y acceso a tres clientes para investigación”.",
        practice: "Escribe la página en módulos. Pide a cinco personas identificar resultado, proceso, esfuerzo, evidencia, precio y siguiente paso sin tu ayuda.",
        deliverable: "Página de oferta completa y prueba de comprensión.",
      },
      {
        number: "18.3",
        title: "Correo, DM y conversación de venta",
        duration: "75 min",
        objective: "Nutrir confianza y calificar interés sin guiones robóticos.",
        concept: "Una secuencia efectiva combina entrega, contexto, método, prueba, objeción e invitación. En mensajes directos, pregunta antes de prescribir. Una conversación de venta diagnostica situación, impacto, objetivo, decisiones previas, ajuste y próximos pasos. La honestidad incluye recomendar no comprar cuando no existe encaje.",
        framework: [
          "Nutrición: una idea útil por mensaje y continuidad clara.",
          "Calificación: situación, urgencia, autoridad, recursos y ajuste.",
          "Diagnóstico: preguntas sobre hechos antes que discursos.",
          "Propuesta: relación explícita entre necesidad, proceso y alcance.",
        ],
        example: "DM: “Vi que descargaste la guía de oferta. ¿Qué parte te cuesta más: elegir una promesa o explicar el proceso?”. La respuesta decide si envías recurso, haces otra pregunta o invitas a conversar.",
        practice: "Escribe cinco correos y un guion flexible de conversación. Practica tres escenarios: buen ajuste, falta de urgencia y necesidad fuera de alcance.",
        deliverable: "Secuencia de nutrición y mapa de conversación de venta.",
      },
      {
        number: "18.4",
        title: "Métricas y experimentos de conversión",
        duration: "75 min",
        objective: "Detectar el cuello de botella y mejorar una variable importante a la vez.",
        concept: "Una tasa aislada no explica el problema. Observa volumen, calidad, etapa y tiempo. Si llegan pocas personas adecuadas, corrige distribución; si leen y no aplican, revisa oferta o fricción; si compran y abandonan, el problema está después de la venta. Optimiza el cuello principal, no el elemento más fácil de cambiar.",
        framework: [
          "Entrada: audiencia, fuente y promesa que atrajo.",
          "Avance: porcentaje y tiempo entre etapas.",
          "Calidad: ajuste, objeciones y resultado posterior.",
          "Experimento: hipótesis, variable, muestra y decisión.",
        ],
        example: "Muchas llamadas y pocas propuestas pueden indicar mala calificación; muchas propuestas y pocas ventas pueden revelar valor, precio o decisión; muchas ventas y reembolsos señalan expectativas o entrega.",
        practice: "Construye un embudo con datos disponibles. Identifica una fuga, escucha diez conversaciones y diseña un experimento de cuatro semanas.",
        deliverable: "Tablero de conversión y plan de experimento prioritario.",
      },
    ],
    mission: {
      title: "Ruta de contenido a cliente",
      brief: "Construye una experiencia completa que permita descubrir, evaluar y comprar una oferta con claridad.",
      steps: [
        "Mapea preguntas y activos por etapa.",
        "Redacta oferta y página con alcance y prueba.",
        "Crea secuencia de cinco mensajes y conversación de diagnóstico.",
        "Define métricas de volumen, avance y calidad.",
        "Diseña un experimento para la fuga principal.",
      ],
      deliverable: "Embudo completo, página, secuencia, guion y tablero de conversión.",
    },
    checklist: [
      "Cada etapa resuelve una duda distinta.",
      "La oferta explica mecanismo, esfuerzo y límites.",
      "La conversación diagnostica antes de proponer.",
      "El CTA indica exactamente qué ocurrirá después.",
      "Optimizo el cuello principal con una hipótesis.",
    ],
    resources: [
      { title: "Mapa de conversión", type: "Plantilla", description: "Etapa, pregunta, activo, CTA, métrica y responsable." },
      { title: "Página de oferta", type: "Plantilla", description: "Promesa, mecanismo, proceso, alcance, prueba, objeciones y decisión." },
      { title: "Tablero de embudo", type: "Tablero", description: "Volumen, avance, calidad, tiempo y aprendizaje por fuente." },
    ],
  },
  {
    number: "19",
    slug: "monetizacion",
    title: "Monetización",
    phase: "Negocio y escala",
    phaseNumber: "04",
    duration: "5 h 30 min",
    promise: "Convertir autoridad y audiencia en un portafolio de ingresos alineado con capacidad, evidencia y resultados del cliente.",
    summary: "Monetizar no es poner precio a seguidores. Es resolver un problema valioso mediante un modelo que puedas entregar con calidad y margen. Evaluarás servicios, productos, educación, membresía, afiliación, patrocinios y licencias; después diseñarás oferta principal, escalera, precio, venta y tablero financiero.",
    outcomes: [
      "Elegir modelos de ingreso según audiencia, problema, prueba y capacidad.",
      "Diseñar una oferta principal con transformación y economía saludable.",
      "Construir una escalera coherente de entrada, núcleo y continuidad.",
      "Planificar venta, entrega y revisión financiera.",
    ],
    lessons: [
      {
        number: "19.1",
        title: "Modelos de ingreso y criterios de elección",
        duration: "75 min",
        objective: "Seleccionar un modelo por ajuste estratégico, no por popularidad.",
        concept: "Cada modelo cambia relación entre tiempo, riesgo, margen y prueba. Servicios permiten aprender y generar caja; grupos y cursos aumentan apalancamiento cuando el método está probado; membresías exigen valor recurrente; patrocinios dependen de audiencia y confianza; licencias requieren propiedad intelectual clara.",
        framework: [
          "Problema: urgencia, frecuencia y valor de resolverlo.",
          "Prueba: evidencia de método y capacidad de entregar.",
          "Economía: precio, costo, margen, adquisición y soporte.",
          "Preferencia: tipo de trabajo y relación que quieres sostener.",
        ],
        example: "Una audiencia pequeña con problema urgente puede sostener consultoría de alto valor antes que un curso económico. El servicio genera lenguaje, casos y método para productos futuros.",
        practice: "Evalúa seis modelos del 1 al 5 en demanda, prueba, margen, capacidad, disfrute y riesgo. Elige uno principal y uno complementario.",
        deliverable: "Matriz de modelos y tesis de monetización de 12 meses.",
      },
      {
        number: "19.2",
        title: "Oferta principal, alcance y precio",
        duration: "85 min",
        objective: "Construir una oferta rentable que promete un cambio claro y controla complejidad.",
        concept: "El precio debe sostener valor, costo, riesgo y estrategia; no nace de horas solamente ni de copiar competidores. Define resultado, método, alcance, soporte, tiempo y condiciones. Calcula capacidad y margen antes de vender. Una oferta con demasiadas opciones aumenta entrega y confusión.",
        framework: [
          "Valor: importancia del problema y calidad del resultado.",
          "Alcance: entregables, revisiones, soporte y responsabilidades.",
          "Economía: horas, herramientas, impuestos, margen y capacidad.",
          "Riesgo: prueba, políticas, condiciones y expectativas.",
        ],
        example: "Un programa de cuatro semanas incluye diagnóstico, sesiones, plantillas y revisión; excluye producción completa. El precio debe cubrir preparación, soporte, entrega, adquisición y margen para mejorar el servicio.",
        practice: "Diseña tres versiones de alcance y calcula horas reales. Selecciona una oferta principal, un límite de clientes y un precio que mantenga margen objetivo.",
        deliverable: "Ficha de oferta, capacidad mensual y modelo de precio.",
      },
      {
        number: "19.3",
        title: "Escalera de valor y portafolio",
        duration: "70 min",
        objective: "Conectar distintas ofertas sin crear productos desconectados.",
        concept: "Una escalera no obliga a comprar en orden; ofrece niveles de problema, apoyo y profundidad. El contenido gratuito ayuda a diagnosticar, una entrada acelera una tarea, la oferta núcleo produce transformación y la continuidad sostiene aplicación. Cada nivel debe tener valor propio.",
        framework: [
          "Gratuito: comprensión, diagnóstico o primera victoria.",
          "Entrada: resultado estrecho con bajo riesgo.",
          "Núcleo: transformación principal y método completo.",
          "Continuidad: implementación, comunidad, soporte o actualización.",
        ],
        example: "Contenido sobre claridad → diagnóstico editable → taller de propuesta → programa de posicionamiento → asesoría trimestral. Cada nivel resuelve un problema distinto y prepara el siguiente.",
        practice: "Mapea las decisiones de tu cliente y crea máximo cuatro niveles. Elimina cualquier oferta que no tenga audiencia, problema o función específica.",
        deliverable: "Escalera de valor y mapa de migración entre ofertas.",
      },
      {
        number: "19.4",
        title: "Venta, lanzamiento y tablero financiero",
        duration: "80 min",
        objective: "Planificar una campaña que valide demanda y proteger la salud económica.",
        concept: "Un lanzamiento es una secuencia de investigación, conversación, educación, oferta, seguimiento y entrega. Comienza con una cohorte pequeña para observar resultados y objeciones. Mide ingresos, margen, cobro, conversión, reembolso, costo de adquisición, capacidad y resultado del cliente.",
        framework: [
          "Preventa: conversaciones, lista de espera y validación de problema.",
          "Campaña: tensión, método, prueba, objeciones y ventana de decisión.",
          "Entrega: onboarding, hitos, soporte y captura de evidencia.",
          "Economía: ingreso cobrado, costos, margen y horas reales.",
        ],
        example: "Antes de grabar 40 clases, vende diez plazas de una cohorte en vivo con alcance claro. Usa preguntas y resultados para mejorar el programa y decidir si convertirlo en producto escalable.",
        practice: "Diseña una campaña de cuatro semanas y un tablero financiero. Define meta, oferta, audiencia, calendario, capacidad, costos y criterios de seguir o cambiar.",
        deliverable: "Plan de lanzamiento y tablero económico de la oferta.",
      },
    ],
    mission: {
      title: "Oferta rentable validada",
      brief: "Diseña, presenta y valida una oferta principal con economía, alcance y campaña completos.",
      steps: [
        "Elige modelo principal y complementario.",
        "Define transformación, método, alcance, capacidad y precio.",
        "Construye una escalera máxima de cuatro niveles.",
        "Planifica campaña y conversaciones de preventa.",
        "Configura tablero de margen y resultado del cliente.",
      ],
      deliverable: "Oferta lista para vender, campaña y modelo financiero.",
    },
    checklist: [
      "El modelo corresponde a mi prueba y capacidad.",
      "La oferta tiene alcance y responsabilidades claros.",
      "Conozco costo, horas, margen y límite mensual.",
      "Cada nivel del portafolio resuelve un problema propio.",
      "Mido resultado del cliente además de ingresos.",
    ],
    resources: [
      { title: "Matriz de monetización", type: "Plantilla", description: "Compara modelos por demanda, prueba, margen, capacidad, riesgo y preferencia." },
      { title: "Calculadora de oferta", type: "Plantilla", description: "Alcance, horas, costos, capacidad, margen y escenarios de precio." },
      { title: "Tablero de lanzamiento", type: "Tablero", description: "Audiencia, conversaciones, ventas, entrega, costos y resultados." },
    ],
  },
  {
    number: "20",
    slug: "escalamiento",
    title: "Escalamiento",
    phase: "Negocio y escala",
    phaseNumber: "04",
    duration: "6 h",
    promise: "Escalar resultados con sistemas, equipo y distribución sin romper la calidad ni convertir al creador en el cuello de botella.",
    summary: "Escalar no es hacer más de todo. Es identificar el motor que ya funciona, estandarizarlo, ampliar capacidad y proteger calidad. Diseñarás procesos, roles, tableros, reuniones, delegación, alianzas, distribución pagada y un plan de 90 días. El objetivo final es un negocio que aprende y opera sin depender de tu memoria.",
    outcomes: [
      "Diagnosticar si existe evidencia suficiente para escalar.",
      "Convertir trabajo repetido en procesos y estándares.",
      "Delegar resultados con contexto, autoridad y control de calidad.",
      "Crear un plan de crecimiento de 90 días con límites financieros y operativos.",
    ],
    lessons: [
      {
        number: "20.1",
        title: "Qué merece escalar",
        duration: "75 min",
        objective: "Distinguir un motor repetible de un pico aislado.",
        concept: "Escala lo que ya produce valor de forma repetible: una audiencia clara, oferta vendible, entrega que consigue resultados y economía saludable. Si una venta depende de esfuerzo heroico o una pieza viral, todavía existe hipótesis, no sistema. Documenta condiciones de éxito y capacidad antes de aumentar demanda.",
        framework: [
          "Demanda: problema frecuente y conversaciones consistentes.",
          "Conversión: mensaje y oferta que funcionan en más de un caso.",
          "Entrega: proceso repetible con calidad observable.",
          "Economía: margen, flujo de caja y capacidad para invertir.",
        ],
        example: "Antes de invertir en anuncios para un curso, confirma ventas orgánicas, finalización, resultados y soporte necesario. La publicidad amplifica tanto el ajuste como la falla.",
        practice: "Evalúa demanda, conversión, entrega y economía con evidencia de los últimos 90 días. Clasifica cada área en roja, amarilla o verde y elige el cuello principal.",
        deliverable: "Diagnóstico de preparación para escala.",
      },
      {
        number: "20.2",
        title: "Sistemas, documentación y calidad",
        duration: "85 min",
        objective: "Transformar conocimiento tácito en procesos que otras personas puedan ejecutar y mejorar.",
        concept: "Documentar no es escribir manuales eternos. Comienza por resultados, decisiones, pasos críticos, ejemplos y definición de terminado. Usa checklist para tareas estables y principios para decisiones complejas. Actualiza el proceso después de errores reales.",
        framework: [
          "Resultado: qué debe existir y para quién.",
          "Estándar: criterios de calidad y ejemplos aprobados.",
          "Proceso: pasos, herramientas, tiempos y responsables.",
          "Mejora: incidencias, aprendizaje y versión siguiente.",
        ],
        example: "Un SOP de publicación incluye brief aprobado, revisión de datos, zonas seguras, caption, derechos, CTA, programación y comprobación final; además muestra una pieza que sí cumple.",
        practice: "Documenta los cinco procesos que más dependen de tu memoria. Pide a otra persona ejecutar uno sin explicación adicional y registra preguntas.",
        deliverable: "Biblioteca inicial de cinco procesos y estándares.",
      },
      {
        number: "20.3",
        title: "Equipo, delegación y cadencia de gestión",
        duration: "90 min",
        objective: "Delegar resultados sin microgestión ni abandono.",
        concept: "Delegar exige contexto, resultado, límites, recursos, autoridad y revisión. Contrata primero alrededor del cuello de botella, no por título de moda. Mantén reuniones breves con métricas, bloqueos, decisiones y aprendizaje. La persona fundadora conserva estrategia y estándares hasta que exista suficiente contexto compartido.",
        framework: [
          "Rol: resultado continuo del que la persona es responsable.",
          "Brief: objetivo, audiencia, estándar, límites y fecha.",
          "Autoridad: decisiones que puede tomar sin permiso.",
          "Cadencia: revisión de trabajo, métricas y desarrollo.",
        ],
        example: "No delegues “haz redes”. Delega “publicar 12 piezas mensuales aprobadas, responder comunidad en 24 horas y entregar un reporte de aprendizajes por serie”, con acceso, ejemplos y límites.",
        practice: "Diseña el primer rol según tu cuello de botella. Escribe scorecard, responsabilidades, autoridad, onboarding de 30 días y reunión semanal.",
        deliverable: "Scorecard del rol, plan de onboarding y sistema de gestión.",
      },
      {
        number: "20.4",
        title: "Distribución, inversión y plan de 90 días",
        duration: "90 min",
        objective: "Expandir un motor probado mediante alianzas, medios y capacidad con límites claros.",
        concept: "Puedes escalar distribución con colaboración, afiliación, prensa, SEO, eventos y publicidad. Cada canal necesita una hipótesis, oferta y sistema de atribución. Define presupuesto de aprendizaje, pérdidas máximas y criterio para aumentar inversión. El plan de escala debe incluir capacidad de entrega y caja, no solo audiencia.",
        framework: [
          "Motor: contenido, oferta y recorrido que ya producen resultados.",
          "Palanca: canal adicional con audiencia y economía compatibles.",
          "Capacidad: personas, soporte, tecnología y calidad disponibles.",
          "Gobierno: presupuesto, métricas, límites y reunión de decisión.",
        ],
        example: "Prueba una alianza con una comunidad complementaria: taller para 100 personas, oferta específica y seguimiento medido. Si calidad y conversión cumplen el umbral, repite antes de abrir tres canales nuevos.",
        practice: "Elige una palanca, diseña un experimento de 30 días y proyecta tres escenarios. Construye un plan trimestral con objetivo, iniciativas, dueños, presupuesto y riesgos.",
        deliverable: "Roadmap de escala de 90 días y tablero ejecutivo.",
      },
    ],
    mission: {
      title: "Plan maestro de escala",
      brief: "Cierra el programa convirtiendo estrategia, contenido, conversión y monetización en un sistema operativo de 90 días.",
      steps: [
        "Diagnostica demanda, conversión, entrega y economía.",
        "Documenta los cinco procesos críticos.",
        "Diseña el rol que resuelve el cuello de botella principal.",
        "Selecciona una palanca de distribución y un presupuesto de aprendizaje.",
        "Define objetivos, iniciativas, dueños, métricas, riesgos y reuniones.",
      ],
      deliverable: "Plan de escala de 90 días, procesos, scorecard de equipo y tablero ejecutivo.",
    },
    checklist: [
      "Existe evidencia repetida antes de ampliar inversión.",
      "La capacidad de entrega crece con la demanda.",
      "Los procesos tienen resultado, estándar y dueño.",
      "Las personas reciben autoridad y contexto suficiente.",
      "El plan incluye presupuesto, límites y riesgos.",
    ],
    resources: [
      { title: "Diagnóstico de escala", type: "Plantilla", description: "Demanda, conversión, entrega, economía, evidencia y riesgo por área." },
      { title: "SOP de una página", type: "Plantilla", description: "Resultado, estándar, pasos, decisiones, ejemplos, dueño y versión." },
      { title: "Scorecard de rol", type: "Plantilla", description: "Resultados, indicadores, responsabilidades, autoridad y onboarding." },
      { title: "Roadmap 90", type: "Tablero", description: "Objetivos, iniciativas, dueños, presupuesto, riesgos y revisión semanal." },
    ],
  },
];
