import type { CourseModuleContent } from "./types";

export const phaseOneModules: CourseModuleContent[] = [
  {
    number: "01",
    slug: "mentalidad-del-creador",
    title: "Mentalidad del Creador",
    phase: "Fundamentos de autoridad",
    phaseNumber: "01",
    duration: "3 h 30 min",
    promise: "Dejar de improvisar y asumir la identidad de un creador que piensa, decide y ejecuta como dueño de un negocio.",
    summary: "Antes de hablar de cámaras, algoritmos o ventas necesitas una identidad operativa. Este módulo cambia el enfoque de “publicar cuando me inspire” por un sistema sostenible: una razón clara para crear, estándares de calidad, hábitos realistas y una meta de 90 días. La creatividad deja de depender del ánimo y comienza a responder a una dirección.",
    outcomes: [
      "Definir una visión concreta para tu marca y tu vida como creador.",
      "Reconocer las creencias que frenan la exposición, la venta y la consistencia.",
      "Diseñar un ritmo semanal que puedas sostener sin agotarte.",
      "Convertir una meta ambigua en un plan de ejecución de 90 días.",
    ],
    lessons: [
      {
        number: "01.1",
        title: "De consumidor a creador-operador",
        duration: "45 min",
        objective: "Adoptar una identidad que combina creatividad, criterio y responsabilidad empresarial.",
        concept: "Un creador estratégico no publica para sentirse ocupado: observa un problema, formula un punto de vista, crea una pieza útil y mide la respuesta. También entiende que su contenido es un activo que puede generar confianza durante meses. La identidad correcta no es “soy influencer”, sino “soy una persona que transforma experiencia en decisiones útiles para una audiencia específica”. Esa identidad permite trabajar incluso cuando una publicación no recibe la reacción esperada.",
        framework: [
          "Creador: convierte ideas en mensajes claros y memorables.",
          "Estratega: conecta cada mensaje con un objetivo de audiencia o negocio.",
          "Operador: protege tiempo, documenta procesos y termina lo que empieza.",
          "Líder: sostiene una opinión propia y acepta aprender en público.",
        ],
        example: "En lugar de decir “quiero subir más Reels”, una consultora declara: “Cada semana convertiré una pregunta real de mis clientes en una explicación de 60 segundos que los ayude a tomar una decisión”. La segunda frase define audiencia, utilidad y ritmo.",
        practice: "Escribe dos columnas: “la forma en que creo hoy” y “la forma en que opera mi versión profesional”. Incluye decisiones sobre tiempo, exposición, aprendizaje, ventas y seguimiento. Elige tres comportamientos que comienzan esta semana.",
        deliverable: "Declaración de identidad del creador en un párrafo y tres compromisos observables.",
      },
      {
        number: "01.2",
        title: "Miedo, perfeccionismo y permiso para publicar",
        duration: "50 min",
        objective: "Separar la calidad real del perfeccionismo que posterga el aprendizaje.",
        concept: "El perfeccionismo suele parecer profesionalismo, pero en contenido funciona como una estrategia para evitar juicio. La calidad se construye con ciclos: publicar, observar, aprender y mejorar. Tu primera versión necesita ser clara, honesta y útil; no definitiva. El miedo baja cuando defines un estándar mínimo de publicación y aceptas que la audiencia evalúa una pieza, no tu valor personal.",
        framework: [
          "Hecho: describe lo que ocurrió sin interpretación.",
          "Historia: identifica lo que tu mente concluyó sobre ese hecho.",
          "Riesgo real: calcula la consecuencia probable, no la imaginada.",
          "Siguiente repetición: decide qué mejorarás en la próxima pieza.",
        ],
        example: "Hecho: un video tuvo 430 vistas. Historia: “a nadie le interesa mi tema”. Riesgo real: perdiste una hora y obtuviste datos. Siguiente repetición: abrir con la pregunta del cliente y cortar la introducción de siete segundos.",
        practice: "Toma tres ideas que no has publicado. Para cada una, escribe qué temes, qué evidencia tienes, cuál sería una versión publicable en 45 minutos y qué aprendizaje quieres obtener.",
        deliverable: "Regla personal de publicación: condiciones mínimas que una pieza debe cumplir para salir.",
      },
      {
        number: "01.3",
        title: "Disciplina creativa sin agotamiento",
        duration: "55 min",
        objective: "Construir un sistema semanal que proteja energía, foco y recuperación.",
        concept: "La consistencia no significa producir todos los días; significa cumplir una promesa editorial durante suficiente tiempo. El sistema más eficiente separa tareas con energías distintas: investigar, pensar, escribir, grabar, editar, publicar y responder. Al agruparlas reduces cambios de contexto y reservas tu mejor energía para el trabajo que solo tú puedes hacer.",
        framework: [
          "Captura diaria: registra preguntas, historias, frases y observaciones.",
          "Bloque de estrategia: elige temas y define el objetivo de cada pieza.",
          "Producción por lotes: escribe o graba varias piezas en una sesión.",
          "Comunidad y revisión: responde, escucha y documenta aprendizajes.",
        ],
        example: "Un profesional con empleo puede dedicar martes 25 minutos a investigar, jueves 60 a guionar, sábado 90 a grabar cuatro videos y 15 minutos diarios a conversación. La frecuencia nace de un calendario real, no de copiar la rutina de un creador a tiempo completo.",
        practice: "Audita una semana normal. Marca horas de alta, media y baja energía. Asigna una tarea creativa a cada tipo y bloquea dos sesiones de producción. Incluye una ventana explícita de descanso.",
        deliverable: "Calendario semanal sostenible con bloques, límites y plan de recuperación.",
      },
      {
        number: "01.4",
        title: "Tu sprint estratégico de 90 días",
        duration: "60 min",
        objective: "Traducir la visión en una meta medible, hábitos de entrada y revisiones semanales.",
        concept: "Noventa días son suficientes para producir evidencia y lo bastante cortos para conservar urgencia. Una buena meta combina resultado y proceso. El resultado indica hacia dónde vas; el proceso define lo que controlas. No persigas simultáneamente alcance, comunidad, producto, podcast, newsletter y ventas. Elige un cuello de botella y organiza el trimestre alrededor de él.",
        framework: [
          "Resultado: una métrica de negocio o audiencia con fecha.",
          "Entradas: acciones semanales completamente bajo tu control.",
          "Evidencia: señales tempranas de que el mensaje está funcionando.",
          "Revisión: reunión semanal contigo para mantener, corregir o eliminar.",
        ],
        example: "Resultado: conseguir 20 conversaciones calificadas en 90 días. Entradas: dos videos educativos, un caso y 15 interacciones profundas por semana. Evidencia: respuestas, guardados, visitas al perfil y mensajes con preguntas específicas.",
        practice: "Elige un objetivo principal, una audiencia, una oferta y un canal. Define tres acciones semanales, una métrica de calidad y una de resultado. Decide qué actividad vas a dejar de hacer durante el sprint.",
        deliverable: "Tablero de 90 días con objetivo, entradas, métricas y doce revisiones semanales.",
      },
    ],
    mission: {
      title: "Manifiesto operativo del creador",
      brief: "Construye el documento que usarás para tomar decisiones cuando falte motivación o aparezcan oportunidades que distraen.",
      steps: [
        "Escribe por qué quieres crear y a quién quieres servir.",
        "Define la transformación que quieres provocar y los valores que no negociarás.",
        "Fija tu estándar mínimo de publicación y tu ritmo semanal realista.",
        "Declara una meta de 90 días y las tres acciones que la alimentan.",
        "Añade una lista de “no haré” para proteger tu foco.",
      ],
      deliverable: "Manifiesto de una página y tablero de ejecución de 90 días.",
    },
    checklist: [
      "Puedo explicar por qué creo contenido en una frase.",
      "Tengo una meta principal para los próximos 90 días.",
      "Mi calendario cabe dentro de mi vida actual.",
      "Sé qué significa “suficientemente bueno para publicar”.",
      "Tengo una revisión semanal programada.",
    ],
    resources: [
      { title: "Manifiesto del creador", type: "Plantilla", description: "Hoja de una página para propósito, valores, estándares y límites." },
      { title: "Sprint de 90 días", type: "Tablero", description: "Seguimiento semanal de entradas, resultados, aprendizajes y próximos experimentos." },
      { title: "Auditoría de energía", type: "Guía", description: "Ejercicio para ubicar tareas creativas en los mejores bloques de tu semana." },
    ],
  },
  {
    number: "02",
    slug: "construccion-de-marca-personal",
    title: "Construcción de Marca Personal",
    phase: "Fundamentos de autoridad",
    phaseNumber: "01",
    duration: "4 h",
    promise: "Convertir tu historia, experiencia y criterio en una marca coherente que la audiencia pueda reconocer, recordar y recomendar.",
    summary: "Una marca personal no es una paleta de colores ni una colección de fotos bonitas. Es la expectativa que construyes en la mente de otros: qué problema ayudas a resolver, cómo piensas, qué experiencia respalda tus ideas y cómo se siente interactuar contigo. En este módulo crearás los fundamentos verbales, visuales y conductuales de una marca con autoridad.",
    outcomes: [
      "Definir propósito, promesa, personalidad y prueba de tu marca.",
      "Transformar experiencias personales en activos de credibilidad.",
      "Crear una voz reconocible sin inventar un personaje.",
      "Construir una guía de marca ligera para mantener coherencia.",
    ],
    lessons: [
      {
        number: "02.1",
        title: "La marca como expectativa",
        duration: "55 min",
        objective: "Entender qué elementos crean una percepción consistente y valiosa.",
        concept: "Tu marca existe en las asociaciones que una persona activa cuando escucha tu nombre. Esas asociaciones nacen de cuatro fuentes: el tema que repites, el problema que resuelves, la forma en que lo explicas y la evidencia que presentas. La coherencia no exige hablar de una sola cosa para siempre; exige que distintas piezas apunten a una misma promesa central.",
        framework: [
          "Propósito: la razón humana por la que este trabajo importa.",
          "Promesa: el cambio concreto que ayudas a conseguir.",
          "Personalidad: la energía y los rasgos con los que comunicas.",
          "Prueba: experiencia, resultados, procesos y casos que sostienen la promesa.",
        ],
        example: "“Ayudo a profesionales brillantes que suenan genéricos a convertir su experiencia en una voz digital clara y vendible”. La frase une audiencia, dolor y transformación; cada contenido puede reforzar una parte de esa expectativa.",
        practice: "Pide a cinco personas que describan en tres palabras cómo te perciben profesionalmente. Compara esas respuestas con las tres palabras por las que deseas ser conocido y detecta la brecha.",
        deliverable: "Mapa de percepción actual versus percepción deseada.",
      },
      {
        number: "02.2",
        title: "Tu inventario de autoridad",
        duration: "60 min",
        objective: "Identificar pruebas y experiencias que te dan derecho a enseñar sin fingir omnisciencia.",
        concept: "La autoridad no requiere ser la persona que más sabe del mundo. Requiere estar suficientemente cerca del problema, haber generado evidencia y comunicar con honestidad el alcance de tu experiencia. Tu carrera, errores, procesos, resultados, preguntas frecuentes y aprendizajes forman un inventario que puede convertirse en casos, historias, tutoriales y opiniones.",
        framework: [
          "Experiencia vivida: problemas que resolviste para ti.",
          "Experiencia aplicada: resultados logrados para clientes o equipos.",
          "Conocimiento estructurado: métodos, estudios y marcos que dominas.",
          "Prueba observable: cifras, antes/después, testimonios, decisiones y artefactos.",
        ],
        example: "Una emprendedora sin miles de seguidores puede enseñar lanzamiento si documenta tres ventas reales, las decisiones que tomó, los mensajes que fallaron y el proceso que repetiría. La especificidad pesa más que una afirmación grandiosa.",
        practice: "Lista 25 activos de autoridad. Para cada uno, anota la lección, la prueba disponible y tres formatos de contenido posibles. Señala cualquier resultado que necesite permiso o anonimización antes de publicarse.",
        deliverable: "Banco de 25 pruebas, experiencias y aprendizajes convertibles en contenido.",
      },
      {
        number: "02.3",
        title: "Voz, personalidad y códigos de reconocimiento",
        duration: "60 min",
        objective: "Diseñar una voz consistente que suene humana en cualquier formato.",
        concept: "La voz de marca no se crea acumulando adjetivos. Se crea tomando decisiones repetibles: qué palabras usas, qué rechazas, cuánto contexto das, cómo confrontas, cómo celebras y qué tipo de humor permites. Los códigos de reconocimiento —frases, estructuras, temas, colores y ritmos— facilitan que la audiencia identifique tu contenido antes de ver el nombre.",
        framework: [
          "Somos / no somos: define contrastes conductuales, no solo cualidades.",
          "Decimos / evitamos: crea un léxico propio y una lista de clichés prohibidos.",
          "Energía: selecciona el nivel de intensidad, cercanía y formalidad.",
          "Firma: elige dos recursos verbales y dos visuales que repetirás.",
        ],
        example: "Una marca puede ser directa pero no agresiva, técnica pero no fría, ambiciosa pero no vendehumo. Puede abrir con una verdad incómoda, explicar con ejemplos cotidianos y cerrar con una pregunta de decisión.",
        practice: "Reescribe el mismo consejo en tres tonos. Elige el que representa tu personalidad y crea diez reglas concretas de voz con ejemplos de “sí” y “no”.",
        deliverable: "Guía de voz con principios, vocabulario, frases de firma y ejemplos.",
      },
      {
        number: "02.4",
        title: "Sistema visual mínimo viable",
        duration: "65 min",
        objective: "Crear coherencia visual sin convertir el diseño en una barrera para publicar.",
        concept: "La identidad visual debe ayudar a reconocer y comprender, no competir con el mensaje. Un sistema mínimo viable incluye jerarquía tipográfica, dos colores principales, reglas de fotografía o video, portada y subtítulos. La repetición deliberada genera reconocimiento; la variación ocurre dentro de límites claros.",
        framework: [
          "Base: fondo, tipografía y contraste accesible.",
          "Acento: un color para atención y otro para información secundaria.",
          "Composición: ubicación repetible de título, rostro, prueba y firma.",
          "Movimiento: reglas para cortes, subtítulos y transiciones.",
        ],
        example: "Una creadora puede usar fondo oscuro, título blanco, palabra clave magenta, plano medio y subtítulos de dos líneas. Cambian los temas y tomas, pero la estructura visual conserva familiaridad.",
        practice: "Crea tres plantillas: portada de video, carrusel educativo y caso de estudio. Prueba cada una en pantalla pequeña y elimina cualquier elemento que no mejore comprensión o reconocimiento.",
        deliverable: "Kit visual mínimo con colores, tipografías, composición y tres plantillas.",
      },
    ],
    mission: {
      title: "Brand One-Page",
      brief: "Condensa la estrategia de tu marca personal en una página que pueda guiar contenido, diseño, colaboraciones y ofertas.",
      steps: [
        "Escribe propósito, audiencia y transformación principal.",
        "Selecciona tres atributos de personalidad y sus límites.",
        "Añade cinco pruebas de autoridad y tres historias de origen.",
        "Define reglas de voz y códigos visuales de reconocimiento.",
        "Redacta una promesa corta que pueda entender alguien fuera de tu industria.",
      ],
      deliverable: "Documento maestro de marca y kit visual mínimo viable.",
    },
    checklist: [
      "Mi marca promete una transformación, no solo habla de un tema.",
      "Puedo demostrar por qué estoy capacitado para enseñar.",
      "Mi voz tiene reglas concretas y reconocibles.",
      "El sistema visual funciona en móvil y es fácil de repetir.",
      "Toda persona que colabore conmigo puede consultar una guía breve.",
    ],
    resources: [
      { title: "Brand One-Page", type: "Plantilla", description: "Resumen editable de propósito, promesa, personalidad, prueba y códigos de marca." },
      { title: "Inventario de autoridad", type: "Plantilla", description: "Matriz para convertir experiencia y resultados en activos editoriales." },
      { title: "Guía de voz", type: "Guía", description: "Sistema de decisiones verbales con ejemplos de uso correcto e incorrecto." },
    ],
  },
  {
    number: "03",
    slug: "avatar",
    title: "Avatar",
    phase: "Fundamentos de autoridad",
    phaseNumber: "01",
    duration: "3 h 45 min",
    promise: "Comprender a una audiencia real con suficiente profundidad para crear mensajes que parezcan escritos para una sola persona.",
    summary: "El avatar no es una ficha inventada con edad, ciudad y color favorito. Es una hipótesis viva sobre una persona que intenta progresar, enfrenta fricciones y usa un lenguaje específico para describirlas. Aprenderás a investigar conversaciones, identificar decisiones y construir un perfil que sirva para contenido, productos y ventas.",
    outcomes: [
      "Diferenciar audiencia amplia, segmento prioritario y comprador ideal.",
      "Investigar problemas usando conversaciones y comportamiento real.",
      "Mapear deseos, obstáculos, objeciones y momentos de decisión.",
      "Construir un dossier de avatar que se actualice con evidencia.",
    ],
    lessons: [
      {
        number: "03.1",
        title: "Segmentar por situación, no por estereotipo",
        duration: "50 min",
        objective: "Elegir una audiencia según el progreso que busca y el contexto en el que decide.",
        concept: "Dos personas con la misma edad pueden necesitar mensajes completamente distintos. La segmentación útil parte de situación, nivel de conciencia, urgencia, recursos y resultado deseado. Tu mejor segmento no siempre es el más grande: es aquel cuyo problema comprendes, al que puedes acceder y para el que tienes una solución creíble.",
        framework: [
          "Situación actual: qué está ocurriendo y por qué busca ayuda ahora.",
          "Progreso deseado: qué quiere poder hacer, sentir o demostrar.",
          "Restricciones: tiempo, dinero, habilidades, autoridad o apoyo.",
          "Accesibilidad: dónde conversa, qué consume y cómo puedes llegar.",
        ],
        example: "“Emprendedores de 25 a 40” es amplio. “Consultores que ya consiguen clientes por referencia pero no saben explicar su valor en redes” define situación, canal, problema y oportunidad.",
        practice: "Propón tres segmentos posibles y califícalos del 1 al 5 en intensidad del problema, capacidad de pago, acceso, experiencia propia y entusiasmo. Elige uno para los próximos 90 días.",
        deliverable: "Matriz de selección y frase del segmento prioritario.",
      },
      {
        number: "03.2",
        title: "Investigación de voz del cliente",
        duration: "60 min",
        objective: "Recolectar palabras, preguntas y contextos reales sin confirmar únicamente tus suposiciones.",
        concept: "La investigación de audiencia busca lenguaje y patrones, no elogios. Las mejores fuentes son entrevistas recientes, mensajes directos, comentarios, llamadas de venta, reseñas, comunidades y búsquedas. Registra frases textuales y sepáralas de tu interpretación. Cuando una misma idea aparece en contextos distintos, tienes una señal editorial fuerte.",
        framework: [
          "Disparador: qué ocurrió antes de empezar a buscar una solución.",
          "Dolor: qué cuesta el problema en tiempo, dinero, identidad o tranquilidad.",
          "Soluciones previas: qué intentó y por qué no funcionó.",
          "Lenguaje: palabras exactas usadas para describir deseo y frustración.",
        ],
        example: "El cliente no dice “necesito optimizar mi posicionamiento”; dice “cuando me preguntan qué hago, doy una explicación de cinco minutos y todavía no queda claro”. Esa frase puede convertirse en gancho, diagnóstico y promesa.",
        practice: "Realiza cinco entrevistas de 20 minutos o analiza 50 comentarios relevantes. No vendas. Pregunta por hechos recientes, decisiones y soluciones intentadas. Subraya frases repetidas.",
        deliverable: "Banco de voz del cliente con al menos 30 citas clasificadas.",
      },
      {
        number: "03.3",
        title: "Mapa de problemas, deseos y objeciones",
        duration: "55 min",
        objective: "Organizar la investigación en un mapa accionable para contenido y oferta.",
        concept: "El problema visible suele esconder consecuencias más profundas. Una persona que “no sabe qué publicar” puede temer parecer irrelevante, perder oportunidades o desperdiciar tiempo. El deseo también tiene capas: resultado funcional, emoción y cambio de identidad. Las objeciones revelan el riesgo que el cliente quiere reducir antes de avanzar.",
        framework: [
          "Problema externo: la situación observable.",
          "Problema interno: emoción o conflicto que la situación produce.",
          "Problema de identidad: lo que teme que esto diga sobre sí mismo.",
          "Objeción: razón concreta para no creer, no priorizar o no comprar.",
        ],
        example: "Externo: no publica con frecuencia. Interno: se siente atrasado. Identidad: cree que no tiene nada original. Objeción: piensa que crear contenido exige horas diarias. El mensaje debe resolver más que el calendario.",
        practice: "Construye una matriz con diez problemas, diez deseos y diez objeciones. Para cada fila agrega evidencia, nivel de urgencia y una idea de contenido que reduzca incertidumbre.",
        deliverable: "Mapa de 30 tensiones priorizadas por evidencia y urgencia.",
      },
      {
        number: "03.4",
        title: "El dossier vivo del avatar",
        duration: "60 min",
        objective: "Sintetizar evidencia sin convertir al avatar en una caricatura rígida.",
        concept: "El dossier debe funcionar como herramienta de decisión. Incluye situación, meta, lenguaje, comportamiento, canales, objeciones y criterios de compra. También declara qué no sabes todavía. Cada conversación, venta o pieza de contenido agrega evidencia y puede modificar la hipótesis.",
        framework: [
          "Contexto: un día típico y el momento que activa la búsqueda.",
          "Decisión: criterios, participantes y riesgo percibido.",
          "Contenido: preguntas, formatos y niveles de profundidad preferidos.",
          "Evidencia pendiente: supuestos que debes validar durante el sprint.",
        ],
        example: "En vez de poner “María, 34, ama el café”, escribe: “María vende servicios por referencia, evita hablar a cámara porque teme sonar improvisada y guarda carruseles con estructuras que pueda aplicar el mismo día”.",
        practice: "Redacta el dossier y entrégaselo a alguien que conozca al segmento. Pídele señalar afirmaciones inventadas, lenguaje poco natural y preguntas que aún faltan.",
        deliverable: "Dossier de avatar basado en evidencia y lista de supuestos por validar.",
      },
    ],
    mission: {
      title: "Sala de escucha",
      brief: "Construye una base de evidencia que alimente mensajes, productos y conversaciones de venta durante todo el programa.",
      steps: [
        "Selecciona un segmento prioritario para 90 días.",
        "Recolecta cinco entrevistas o 50 fragmentos de conversación.",
        "Clasifica citas en problemas, deseos, objeciones y disparadores.",
        "Redacta un dossier de avatar usando frases reales.",
        "Define cinco preguntas que continuarás investigando.",
      ],
      deliverable: "Dossier de avatar, banco de citas y matriz de tensiones.",
    },
    checklist: [
      "Mi segmento está definido por una situación concreta.",
      "Tengo evidencia textual, no solo intuiciones.",
      "Conozco el costo emocional y práctico del problema.",
      "Puedo nombrar las objeciones sin ridiculizarlas.",
      "Sé qué supuestos debo validar a continuación.",
    ],
    resources: [
      { title: "Guion de entrevista", type: "Guía", description: "Preguntas abiertas para investigar hechos, lenguaje, decisiones y soluciones previas." },
      { title: "Banco de voz del cliente", type: "Plantilla", description: "Matriz para capturar citas, fuente, contexto, patrón y posible uso editorial." },
      { title: "Dossier del avatar", type: "Plantilla", description: "Perfil vivo de situación, progreso, objeciones, canales y evidencia pendiente." },
    ],
  },
  {
    number: "04",
    slug: "posicionamiento",
    title: "Posicionamiento",
    phase: "Fundamentos de autoridad",
    phaseNumber: "01",
    duration: "4 h",
    promise: "Ocupar una idea clara en la mente de tu audiencia para dejar de competir como una opción genérica.",
    summary: "Posicionarte no es decir que eres diferente; es elegir un contexto donde tu diferencia importa. Definirás la categoría, el problema prioritario, tu punto de vista, la alternativa contra la que compites y una promesa específica. El resultado será un mensaje fácil de entender y suficientemente distinto para despertar curiosidad.",
    outcomes: [
      "Elegir una categoría comprensible sin quedar atrapado en etiquetas genéricas.",
      "Formular un punto de vista que guíe tu contenido y tus decisiones.",
      "Construir una propuesta de valor con transformación y prueba.",
      "Reescribir biografía, presentación y mensaje central de la marca.",
    ],
    lessons: [
      {
        number: "04.1",
        title: "Categoría, contexto y competencia real",
        duration: "55 min",
        objective: "Definir el marco mental en el que quieres ser evaluado.",
        concept: "La categoría le dice al cerebro con qué compararte. Si es demasiado amplia, pareces intercambiable; si es inventada, nadie entiende qué ofreces. La competencia real puede ser otro proveedor, hacerlo internamente, seguir improvisando o no actuar. El mejor posicionamiento hace visible el costo de la alternativa actual.",
        framework: [
          "Categoría conocida: el punto de entrada que la audiencia ya entiende.",
          "Especialización: audiencia, problema, método o contexto que te enfoca.",
          "Alternativa: qué hace hoy el cliente si no te elige.",
          "Cambio de criterio: por qué debería evaluar la solución de otra manera.",
        ],
        example: "No eres simplemente “social media manager”; puedes ser “sistema editorial para expertos que venden servicios complejos”. La categoría es reconocible, pero la especialización cambia la comparación.",
        practice: "Completa: “La mayoría resuelve ___ haciendo ___. Eso falla cuando ___. Nosotros abordamos ___ mediante ___”. Crea cinco versiones y prueba comprensión con personas ajenas a tu sector.",
        deliverable: "Mapa de categoría, alternativas y criterio diferenciador.",
      },
      {
        number: "04.2",
        title: "Tu punto de vista estratégico",
        duration: "60 min",
        objective: "Convertir experiencia y observación en una opinión útil y defendible.",
        concept: "Una marca recordable no solo comparte información: interpreta. El punto de vista explica qué está cambiando, qué práctica común ya no funciona, qué cree la marca y qué recomienda hacer. No se trata de provocar por provocar; se trata de ofrecer una lente que ayude a decidir.",
        framework: [
          "Tensión: una verdad incómoda que la audiencia reconoce.",
          "Creencia: la interpretación que propones.",
          "Consecuencia: qué ocurre si la audiencia sigue igual.",
          "Camino: el principio o método que sugieres adoptar.",
        ],
        example: "Tensión: publicar más no corrige un mensaje confuso. Creencia: la consistencia amplifica lo que ya existe. Consecuencia: producirás más piezas que nadie recuerda. Camino: clarifica promesa y pilares antes de aumentar frecuencia.",
        practice: "Escribe diez prácticas de tu industria con las que estás de acuerdo o en desacuerdo. Para cada una, añade evidencia, matiz y una recomendación. Selecciona tres que puedan sostener una serie de contenidos.",
        deliverable: "Tres tesis editoriales con evidencia y límites.",
      },
      {
        number: "04.3",
        title: "Propuesta de valor y promesa creíble",
        duration: "60 min",
        objective: "Expresar el valor de tu trabajo en términos de progreso, mecanismo y reducción de riesgo.",
        concept: "Una propuesta de valor fuerte responde para quién, qué cambio, mediante qué enfoque y por qué creer. Evita resultados universales o garantizados. La promesa gana fuerza cuando combina especificidad con credibilidad: describe el progreso que facilitas y las condiciones necesarias para alcanzarlo.",
        framework: [
          "Audiencia: persona y situación prioritaria.",
          "Resultado: cambio observable que valora.",
          "Mecanismo: proceso o principio que explica cómo.",
          "Prueba y condiciones: evidencia disponible y responsabilidad del cliente.",
        ],
        example: "“Ayudo a consultores con experiencia a convertir sus ideas dispersas en un sistema semanal de contenido que genera conversaciones comerciales, usando investigación de audiencia, series editoriales y revisión de métricas”.",
        practice: "Redacta diez propuestas. Elimina adjetivos vacíos, promesas que no puedes probar y tecnicismos. Pide a tres personas que expliquen con sus palabras qué entendieron.",
        deliverable: "Propuesta de valor principal, versión corta y versión conversacional.",
      },
      {
        number: "04.4",
        title: "Aplicar el posicionamiento en cada punto de contacto",
        duration: "65 min",
        objective: "Alinear perfil, contenido, casos, ofertas y llamadas a la acción.",
        concept: "El posicionamiento se debilita cuando cada punto de contacto promete algo distinto. Perfil, publicaciones fijadas, página, testimonios y ofertas deben repetir la misma transformación desde ángulos complementarios. La repetición estratégica no aburre: enseña a la audiencia cómo recordarte.",
        framework: [
          "Perfil: quién, problema, resultado y siguiente acción.",
          "Contenido fijado: punto de vista, prueba y método.",
          "Casos: evidencia organizada alrededor de la promesa.",
          "Oferta: alcance y mecanismo coherentes con el mensaje público.",
        ],
        example: "Si tu promesa es claridad estratégica, no fijes únicamente tendencias. Fija una pieza que diagnostique el problema, otra que muestre el método y un caso donde la claridad cambió una decisión o resultado.",
        practice: "Audita biografía, banner, enlaces, piezas fijadas, propuesta y presentación. Marca contradicciones y actualiza primero los tres puntos con mayor tráfico.",
        deliverable: "Perfil reescrito y plan de alineación de puntos de contacto.",
      },
    ],
    mission: {
      title: "Kit de posicionamiento",
      brief: "Crea el conjunto de mensajes que permitirá presentarte de forma consistente en perfil, contenido, reuniones y ofertas.",
      steps: [
        "Define categoría, especialización y alternativa actual del cliente.",
        "Redacta tres tesis que expresen tu punto de vista.",
        "Construye una propuesta de valor con mecanismo y prueba.",
        "Escribe biografía de perfil, pitch de 30 segundos y presentación de 150 palabras.",
        "Diseña tres publicaciones fijadas: visión, método y evidencia.",
      ],
      deliverable: "Documento de posicionamiento y actualización de los principales puntos de contacto.",
    },
    checklist: [
      "Mi audiencia entiende rápidamente en qué categoría participo.",
      "Tengo una diferencia relevante, no solamente estética.",
      "Mi punto de vista puede sostener contenido recurrente.",
      "La promesa es específica y creíble.",
      "Perfil, prueba y oferta cuentan la misma historia.",
    ],
    resources: [
      { title: "Mapa de posicionamiento", type: "Plantilla", description: "Categoría, alternativas, tensiones, criterios y espacio que quieres ocupar." },
      { title: "Constructor de propuesta de valor", type: "Guía", description: "Preguntas y fórmulas para redactar, probar y simplificar tu promesa." },
      { title: "Auditoría de puntos de contacto", type: "Plantilla", description: "Revisión de coherencia entre perfil, contenido, casos y oferta." },
    ],
  },
  {
    number: "05",
    slug: "psicologia-del-consumidor",
    title: "Psicología del Consumidor",
    phase: "Fundamentos de autoridad",
    phaseNumber: "01",
    duration: "4 h",
    promise: "Diseñar mensajes y experiencias que faciliten decisiones sin manipular a la audiencia.",
    summary: "Las personas no toman decisiones procesando toda la información disponible. Filtran, comparan, evitan riesgos y buscan señales de confianza. Este módulo enseña principios de atención, motivación, prueba y fricción para comunicar de forma persuasiva y ética. Aprenderás a reducir incertidumbre, no a fabricar urgencia falsa.",
    outcomes: [
      "Captar atención conectando con relevancia, contraste y claridad.",
      "Distinguir deseos funcionales, emocionales y sociales.",
      "Reducir riesgo mediante prueba, especificidad y reversibilidad.",
      "Aplicar persuasión ética en contenido, ofertas y llamadas a la acción.",
    ],
    lessons: [
      {
        number: "05.1",
        title: "Cómo funciona la atención",
        duration: "55 min",
        objective: "Diseñar entradas que ayuden al cerebro a decidir rápidamente por qué vale la pena continuar.",
        concept: "La atención es selectiva. Una persona detiene el desplazamiento cuando reconoce relevancia, novedad, riesgo, deseo o una pregunta pendiente. El gancho no debe engañar: abre un vacío que el contenido realmente cierra. Claridad y especificidad suelen superar a la exageración porque reducen el esfuerzo necesario para entender.",
        framework: [
          "Relevancia: nombra una situación que la audiencia reconoce.",
          "Contraste: muestra diferencia entre expectativa y realidad.",
          "Consecuencia: explica qué está en juego.",
          "Promesa de cierre: anticipa la utilidad que recibirá al continuar.",
        ],
        example: "“Si tus clientes llegan por recomendación pero tus redes no generan una sola conversación, probablemente no tienes un problema de frecuencia: tienes un problema de traducción de valor”.",
        practice: "Escribe diez ganchos para un mismo tema usando situación, error, contraste, demostración y pregunta. Evalúalos por claridad, relevancia y capacidad de ser cumplidos.",
        deliverable: "Biblioteca de 25 ganchos éticos clasificados por mecanismo de atención.",
      },
      {
        number: "05.2",
        title: "Motivación y capas del deseo",
        duration: "60 min",
        objective: "Conectar una solución con el progreso funcional, emocional y social que la persona busca.",
        concept: "Una compra o cambio de comportamiento rara vez responde a una sola razón. El resultado funcional resuelve una tarea; el emocional modifica cómo la persona quiere sentirse; el social influye en cómo desea ser percibida. Un buen mensaje no inventa inseguridades: refleja motivaciones que la investigación ya reveló.",
        framework: [
          "Funcional: qué podrá hacer o evitar.",
          "Emocional: cómo quiere sentirse durante y después del proceso.",
          "Social: qué quiere demostrar o proteger frente a otros.",
          "Identidad: en qué tipo de persona desea convertirse.",
        ],
        example: "Un calendario de contenido no solo organiza publicaciones. Puede devolver tranquilidad, ayudar a presentarse como profesional y reforzar la identidad de alguien que cumple lo que promete.",
        practice: "Selecciona tres problemas del avatar y describe sus cuatro capas de deseo. Redacta un mensaje funcional y otro que integre emoción e identidad sin exagerar.",
        deliverable: "Mapa de motivaciones para los tres problemas prioritarios.",
      },
      {
        number: "05.3",
        title: "Confianza, prueba y reducción de riesgo",
        duration: "60 min",
        objective: "Construir credibilidad antes de pedir una decisión.",
        concept: "La audiencia evalúa dos preguntas: “¿funciona?” y “¿funcionará para alguien como yo?”. La prueba efectiva es relevante, específica y trazable. Un testimonio genérico vale menos que una historia con punto de partida, proceso y resultado. Cuando no tienes grandes cifras, puedes mostrar demostraciones, decisiones, procesos, artefactos y límites honestos.",
        framework: [
          "Prueba de resultado: cambio medible o observable.",
          "Prueba de proceso: método aplicado y decisiones tomadas.",
          "Prueba de semejanza: caso comparable al lector.",
          "Reducción de riesgo: muestra alcance, condiciones, pasos y salida.",
        ],
        example: "En vez de “excelente asesoría”, presenta: “Llegó con seis servicios sin jerarquía; después de dos sesiones salió con una oferta principal, página reescrita y cinco conversaciones en el primer mes”.",
        practice: "Audita tus pruebas. Convierte tres testimonios vagos en mini casos pidiendo contexto adicional. Si todavía no tienes clientes, documenta un caso propio o una demostración completa.",
        deliverable: "Biblioteca inicial de pruebas organizada por objeción.",
      },
      {
        number: "05.4",
        title: "Arquitectura de decisiones y persuasión ética",
        duration: "65 min",
        objective: "Facilitar el siguiente paso con claridad, autonomía y expectativas correctas.",
        concept: "Persuadir éticamente significa ayudar a una persona adecuada a tomar una decisión informada. Elimina fricción innecesaria, pero conserva información importante. No uses escasez inventada, vergüenza, promesas absolutas ni resultados falsos. Una llamada a la acción fuerte explica qué hacer, qué ocurre después, para quién es y cuándo no conviene.",
        framework: [
          "Claridad: una acción principal y un resultado inmediato.",
          "Capacidad: instrucciones, tiempo y esfuerzo necesarios.",
          "Seguridad: expectativas, privacidad, garantías y límites.",
          "Autonomía: permiso explícito para evaluar y decir no.",
        ],
        example: "“Descarga la guía, completa el diagnóstico de diez minutos y úsalo para elegir tu prioridad editorial. No necesitas comprar nada después”. La acción y la expectativa están claras.",
        practice: "Revisa cinco llamadas a la acción propias. Elimina ambigüedad, presión artificial y pasos ocultos. Añade contexto para que una persona pueda decidir si es el siguiente paso correcto.",
        deliverable: "Banco de CTA éticos para atención, conversación, registro y venta.",
      },
    ],
    mission: {
      title: "Laboratorio de decisión",
      brief: "Rediseña una pieza y una oferta para que capten atención, comuniquen valor y reduzcan incertidumbre sin tácticas manipuladoras.",
      steps: [
        "Selecciona un problema y mapea las cuatro capas de deseo.",
        "Escribe cinco entradas con mecanismos de atención distintos.",
        "Añade una prueba relevante para la objeción principal.",
        "Explica proceso, esfuerzo, límites y siguiente paso.",
        "Realiza una auditoría ética antes de publicar.",
      ],
      deliverable: "Pieza persuasiva completa, matriz de motivaciones y auditoría ética.",
    },
    checklist: [
      "El gancho cumple la promesa que abre.",
      "El mensaje refleja deseos encontrados en investigación.",
      "La prueba incluye contexto y no exagera causalidad.",
      "La llamada a la acción explica qué ocurrirá después.",
      "No uso urgencia, escasez ni vergüenza inventadas.",
    ],
    resources: [
      { title: "Mapa de motivaciones", type: "Plantilla", description: "Capas funcional, emocional, social y de identidad aplicadas a un problema." },
      { title: "Biblioteca de pruebas", type: "Plantilla", description: "Organiza testimonios, casos, demostraciones y procesos por objeción." },
      { title: "Auditoría de persuasión ética", type: "Guía", description: "Checklist para revisar claridad, evidencia, autonomía y expectativas." },
    ],
  },
];
