import type { CourseModuleContent } from "./types";

export const phaseTwoModules: CourseModuleContent[] = [
  {
    number: "06",
    slug: "storytelling",
    title: "Storytelling",
    phase: "Mensaje y contenido",
    phaseNumber: "02",
    duration: "4 h",
    promise: "Transformar experiencias, ideas y casos en historias que enseñan, generan confianza y mueven a la acción.",
    summary: "Contar historias no significa dramatizar cada publicación. Significa organizar información alrededor de tensión, decisiones y cambio. Aprenderás a encontrar historias en tu vida y tu trabajo, elegir la estructura correcta y conectar cada relato con una idea estratégica sin convertirlo en un discurso de venta disfrazado.",
    outcomes: [
      "Construir un banco de historias personales, profesionales y de clientes.",
      "Usar tensión, detalle y cambio para mantener atención.",
      "Aplicar estructuras breves y largas según el formato.",
      "Conectar historia, aprendizaje y acción con naturalidad.",
    ],
    lessons: [
      {
        number: "06.1",
        title: "La unidad mínima de una historia",
        duration: "55 min",
        objective: "Reconocer qué convierte una anécdota en una historia con significado.",
        concept: "Una historia útil contiene alguien que quiere algo, una fuerza que lo dificulta, una decisión y un cambio. El contexto solo importa si aumenta comprensión o tensión. En contenido estratégico, la historia no termina con “y esto me pasó”; termina con una idea que la audiencia puede aplicar a su propia situación.",
        framework: [
          "Estado inicial: qué quería la persona y qué creía al comenzar.",
          "Tensión: obstáculo, contradicción o costo que impide avanzar.",
          "Decisión: acción específica que cambia la dirección.",
          "Transformación: resultado y nueva creencia que queda disponible.",
        ],
        example: "“Durante tres meses publiqué consejos diarios y no recibí una consulta. Cuando revisé mis piezas, descubrí que explicaban qué hacer pero nunca para quién ni por qué yo. Reescribí tres casos desde el problema del cliente y la primera semana llegaron cuatro conversaciones”.",
        practice: "Toma cinco anécdotas y marca deseo, tensión, decisión y cambio. Elimina antecedentes que no alteran el resultado y escribe el aprendizaje en una frase.",
        deliverable: "Cinco historias de 150 palabras con aprendizaje explícito.",
      },
      {
        number: "06.2",
        title: "Tu banco de historias",
        duration: "60 min",
        objective: "Crear una reserva de relatos para no depender de la inspiración.",
        concept: "Las historias aparecen en momentos de primera vez, fracaso, conflicto, sorpresa, cambio de opinión, cliente, mentor y decisión difícil. Registrar detalles cerca del momento conserva lenguaje, emoción y contexto. También debes clasificar sensibilidad: público, anonimizado, privado o sujeto a permiso.",
        framework: [
          "Origen: momentos que explican por qué haces este trabajo.",
          "Proceso: decisiones, pruebas y errores detrás del resultado.",
          "Cliente: transformación con consentimiento y contexto.",
          "Punto de vista: experiencia que cambió una creencia profesional.",
        ],
        example: "Una lista de historias puede incluir: la primera propuesta rechazada, la pregunta que cambió una campaña, el error de cobrar sin alcance definido y el mensaje de un cliente que reveló el verdadero valor del servicio.",
        practice: "Crea una línea de tiempo profesional y personal. Genera al menos 40 semillas de historia y etiqueta tema, emoción, aprendizaje, prueba y nivel de privacidad.",
        deliverable: "Banco de 40 historias con etiquetas y permiso de uso.",
      },
      {
        number: "06.3",
        title: "Estructuras para contenido breve y profundo",
        duration: "60 min",
        objective: "Elegir una arquitectura narrativa según objetivo, tiempo y nivel de conciencia.",
        concept: "No existe una estructura universal. Una historia de 30 segundos necesita entrar cerca del conflicto; una pieza larga puede construir contexto y mostrar varios intentos. La estructura debe servir a la idea, no sentirse como una fórmula visible. Domina pocas arquitecturas y adapta el ritmo.",
        framework: [
          "Antes–quiebre–después: ideal para cambios claros y casos.",
          "Problema–intento–descubrimiento: muestra aprendizaje y método.",
          "Escena–significado–aplicación: convierte un momento pequeño en enseñanza.",
          "Creencia–evidencia–nueva creencia: útil para liderazgo de pensamiento.",
        ],
        example: "Escena: una clienta borra el mismo guion cinco veces. Significado: no le faltan ideas, le falta permiso para hablar con claridad. Aplicación: primero define una sola persona y una sola decisión; después escribe.",
        practice: "Cuenta la misma historia usando dos estructuras y dos duraciones: 45 segundos y 500 palabras. Compara qué detalles cambian y qué idea permanece.",
        deliverable: "Cuatro guiones narrativos listos para formatos distintos.",
      },
      {
        number: "06.4",
        title: "Historias que venden sin forzar",
        duration: "65 min",
        objective: "Usar relatos para reducir incertidumbre y demostrar transformación.",
        concept: "Una historia comercial efectiva no convierte al producto en héroe. El protagonista es la persona que toma decisiones; tu método actúa como guía. Incluye punto de partida, objeción, proceso, evidencia y condición de éxito. La llamada a la acción debe continuar la conversación, no romperla con una oferta sin contexto.",
        framework: [
          "Identificación: una situación que el prospecto reconoce.",
          "Mecanismo: la decisión o proceso que produjo avance.",
          "Prueba: resultado y señales concretas, con sus límites.",
          "Puente: invitación para evaluar si el método aplica al lector.",
        ],
        example: "Después de mostrar cómo una consultora pasó de seis servicios dispersos a una oferta principal, el CTA puede ser: “Si también explicas demasiado y vendes poco, usa esta lista para detectar dónde se rompe tu mensaje”.",
        practice: "Convierte un testimonio en historia de caso. Elimina afirmaciones no verificables, agrega decisiones y cierra con una acción proporcional al nivel de confianza.",
        deliverable: "Caso narrativo largo y tres adaptaciones breves.",
      },
    ],
    mission: {
      title: "Historia insignia",
      brief: "Crea la historia que explica tu origen, tu punto de vista y la transformación que hoy ayudas a conseguir.",
      steps: [
        "Selecciona un momento que cambió tu manera de pensar.",
        "Reconstruye escena, tensión, decisión, costo y resultado.",
        "Extrae una enseñanza directamente ligada a tu posicionamiento.",
        "Escribe versiones de 60 segundos, 300 y 800 palabras.",
        "Prueba la versión breve y registra dónde la audiencia pierde atención.",
      ],
      deliverable: "Historia insignia multiformato y banco de 40 semillas narrativas.",
    },
    checklist: [
      "La historia contiene deseo, tensión, decisión y cambio.",
      "Los detalles sirven al significado.",
      "La enseñanza es aplicable y no moraliza.",
      "Tengo permiso para usar historias de terceros.",
      "La llamada a la acción continúa naturalmente el relato.",
    ],
    resources: [
      { title: "Banco de historias", type: "Plantilla", description: "Archivo para semillas, escenas, emociones, aprendizajes y nivel de privacidad." },
      { title: "Arquitecturas narrativas", type: "Guía", description: "Ocho estructuras con usos recomendados para video, carrusel, correo y caso." },
      { title: "Constructor de casos", type: "Plantilla", description: "Convierte testimonios y resultados en relatos específicos y verificables." },
    ],
  },
  {
    number: "07",
    slug: "copywriting",
    title: "Copywriting",
    phase: "Mensaje y contenido",
    phaseNumber: "02",
    duration: "4 h 15 min",
    promise: "Escribir mensajes claros, específicos y persuasivos que conviertan atención en comprensión y comprensión en acción.",
    summary: "El copywriting no es decorar frases; es tomar decisiones sobre qué decir, en qué orden y con qué evidencia. Partirás de la voz del cliente para crear titulares, argumentos, transiciones y llamadas a la acción. El objetivo es reducir esfuerzo mental y ayudar a la audiencia a reconocer un problema, entender una solución y elegir el siguiente paso.",
    outcomes: [
      "Extraer mensajes de investigación en lugar de inventarlos frente a una pantalla.",
      "Escribir titulares que combinan relevancia, claridad y curiosidad.",
      "Construir argumentos con problema, mecanismo, prueba y objeciones.",
      "Crear CTA específicos para distintas etapas de confianza.",
    ],
    lessons: [
      {
        number: "07.1",
        title: "La investigación escribe el primer borrador",
        duration: "55 min",
        objective: "Convertir voz del cliente, prueba y oferta en materia prima organizada.",
        concept: "La página en blanco se vuelve difícil cuando intentas crear argumento y lenguaje al mismo tiempo. Antes de escribir, reúne citas del cliente, hechos del producto, resultados, objeciones y límites. Clasifica el material por conciencia: problema, solución, producto y decisión. Así eliges qué necesita escuchar la persona ahora.",
        framework: [
          "Problema: síntomas, costos y lenguaje usado para describirlos.",
          "Deseo: resultado, emoción y criterio de éxito.",
          "Mecanismo: por qué tu enfoque funciona de manera distinta.",
          "Prueba: evidencia adecuada para cada afirmación.",
        ],
        example: "Cita: “Publico, pero cuando alguien pregunta qué hago envío un audio de cinco minutos”. Titular derivado: “Si necesitas cinco minutos para explicar tu servicio, tu cliente necesita demasiado esfuerzo para recordarlo”.",
        practice: "Crea un documento de investigación para una oferta. Copia 20 citas, diez hechos, cinco pruebas, diez objeciones y los límites de la solución. No redactes todavía.",
        deliverable: "Brief de copy con evidencia y mensajes priorizados.",
      },
      {
        number: "07.2",
        title: "Titulares, ganchos y primeras líneas",
        duration: "60 min",
        objective: "Conseguir atención calificada sin sacrificar confianza.",
        concept: "El titular debe permitir que la persona correcta se reconozca y anticipe valor. La curiosidad funciona cuando existe una brecha específica; el misterio vacío atrae clics que no convierten. Escribe muchas opciones y selecciona por alineación con audiencia, promesa y prueba disponible.",
        framework: [
          "Resultado específico: el progreso que la audiencia desea.",
          "Situación reconocible: momento, error o síntoma concreto.",
          "Mecanismo: método, descubrimiento o contraste que da novedad.",
          "Calificador: indica para quién aplica o bajo qué condición.",
        ],
        example: "Débil: “El secreto del éxito”. Fuerte: “Cómo convertir una hora de conversación con clientes en diez ideas de contenido que responden preguntas reales”.",
        practice: "Escribe 30 titulares para la misma pieza: diez de resultado, diez de problema y diez de mecanismo. Elige cinco y pide a lectores que expliquen qué esperan encontrar.",
        deliverable: "Swipe file propio con 50 titulares probados y etiquetados.",
      },
      {
        number: "07.3",
        title: "El cuerpo del mensaje",
        duration: "65 min",
        objective: "Ordenar argumentos para sostener atención, explicar valor y resolver dudas.",
        concept: "El cuerpo efectivo alterna afirmación, explicación, ejemplo y prueba. Cada sección responde una pregunta que aparece en la mente del lector: ¿por qué importa?, ¿por qué sucede?, ¿qué hago?, ¿por qué creer?, ¿aplica a mí? Los subtítulos y transiciones convierten una idea compleja en una secuencia fácil de recorrer.",
        framework: [
          "Diagnóstico: nombra el problema de forma más útil que el lector.",
          "Mecanismo: explica la causa y el principio de solución.",
          "Demostración: muestra ejemplo, proceso o contraste.",
          "Objeción: reconoce límites, esfuerzo y alternativas.",
        ],
        example: "Afirmación: “La frecuencia no corrige confusión”. Explicación: amplifica el mensaje existente. Ejemplo: 30 publicaciones con cinco servicios distintos. Prueba: después de elegir una oferta, las visitas al perfil se convierten en conversaciones.",
        practice: "Toma una pieza larga y etiqueta cada párrafo según su función. Elimina repeticiones, agrega ejemplos donde solo hay afirmaciones y reordena para responder dudas en secuencia.",
        deliverable: "Artículo o guion de 800 palabras con arquitectura argumental visible.",
      },
      {
        number: "07.4",
        title: "CTA y copy de oferta",
        duration: "65 min",
        objective: "Pedir la acción correcta según intención y nivel de confianza.",
        concept: "Una llamada a la acción no compensa una oferta confusa. Define acción, beneficio inmediato, esfuerzo y siguiente paso. Para contenido frío, una acción pequeña —guardar, responder, descargar— suele ser proporcional. Para una audiencia preparada, puedes invitar a diagnóstico, conversación o compra con criterios claros.",
        framework: [
          "Acción: verbo específico y una sola prioridad.",
          "Resultado inmediato: qué obtiene al completar el paso.",
          "Fricción: tiempo, información o compromiso requerido.",
          "Continuidad: qué ocurrirá después y cómo puede salir.",
        ],
        example: "“Responde CLARIDAD y te envío la hoja para convertir tus cinco servicios en una oferta principal. Son diez preguntas y no abre una conversación de venta automática”.",
        practice: "Escribe CTA para cuatro niveles: consumo, interacción, captura y venta. Revisa que cada uno cumpla exactamente lo prometido y que no oculte el siguiente paso.",
        deliverable: "Biblioteca de 20 CTA y una secuencia de venta de cinco mensajes.",
      },
    ],
    mission: {
      title: "Página de mensaje maestro",
      brief: "Redacta la pieza central de una oferta usando voz del cliente, mecanismo, prueba y objeciones.",
      steps: [
        "Completa el brief de investigación y elige un nivel de conciencia.",
        "Escribe 30 titulares y selecciona uno por claridad, no por gusto.",
        "Desarrolla problema, mecanismo, proceso, prueba y objeciones.",
        "Añade una llamada a la acción con expectativa completa.",
        "Edita en tres pasadas: estructura, claridad y ritmo.",
      ],
      deliverable: "Página o guion de venta corto, más banco de titulares y CTA.",
    },
    checklist: [
      "El texto usa palabras reales de la audiencia.",
      "Cada afirmación importante tiene explicación o prueba.",
      "Los titulares atraen a la persona correcta.",
      "El texto puede escanearse sin perder la idea principal.",
      "El CTA indica acción, beneficio y siguiente paso.",
    ],
    resources: [
      { title: "Brief de copy", type: "Plantilla", description: "Voz del cliente, problema, deseo, mecanismo, prueba, objeción y oferta." },
      { title: "Banco de titulares", type: "Plantilla", description: "Matriz de 30 ángulos para resultado, problema, mecanismo y prueba." },
      { title: "Editor en tres pasadas", type: "Guía", description: "Proceso para revisar estructura, claridad, ritmo, evidencia y CTA." },
    ],
  },
  {
    number: "08",
    slug: "pilares-de-contenido",
    title: "Pilares de Contenido",
    phase: "Mensaje y contenido",
    phaseNumber: "02",
    duration: "4 h",
    promise: "Diseñar un sistema editorial que genere ideas relevantes, equilibre autoridad y conversión, y elimine la improvisación semanal.",
    summary: "Los pilares no son cinco temas elegidos porque te gustan. Son territorios estratégicos con una función: atraer a la audiencia correcta, profundizar confianza, demostrar método, responder objeciones y mover hacia una oferta. Construirás pilares, series, formatos y un calendario que parte de preguntas reales.",
    outcomes: [
      "Definir pilares conectados con audiencia, posicionamiento y negocio.",
      "Crear series reconocibles dentro de cada pilar.",
      "Mapear ideas a formatos según intención y profundidad.",
      "Construir un calendario de 30 días sostenible y medible.",
    ],
    lessons: [
      {
        number: "08.1",
        title: "La arquitectura editorial",
        duration: "55 min",
        objective: "Asignar una función concreta a cada territorio de contenido.",
        concept: "Una estrategia editorial debe cubrir el viaje de confianza. Algunas piezas ayudan a reconocer un problema; otras enseñan un método, muestran prueba, revelan personalidad o presentan una oferta. Si todo educa pero nada diferencia, te vuelves útil y olvidable. Si todo vende, no construyes suficiente contexto.",
        framework: [
          "Descubrimiento: problemas, preguntas y contrastes de alto interés.",
          "Autoridad: método, análisis, profundidad y punto de vista.",
          "Confianza: historias, procesos, valores y detrás de escena.",
          "Conversión: casos, objeciones, oferta y próximos pasos.",
        ],
        example: "Para una asesora de marca: claridad de mensaje atrae; posicionamiento demuestra método; historias de decisiones construyen confianza; auditorías y casos preparan conversión.",
        practice: "Audita tus últimas 30 piezas y clasifícalas por función. Detecta exceso, vacío y desconexión con la oferta. Propón cuatro pilares con una responsabilidad distinta.",
        deliverable: "Mapa editorial con cuatro pilares y función estratégica.",
      },
      {
        number: "08.2",
        title: "De pilares a series reconocibles",
        duration: "60 min",
        objective: "Convertir temas amplios en formatos repetibles que la audiencia pueda anticipar.",
        concept: "Una serie reduce el costo de ideación y aumenta reconocimiento. Define una promesa, una estructura y una frecuencia. El tema cambia; el contenedor permanece. Las mejores series nacen de preguntas recurrentes, decisiones difíciles, errores observables o análisis que tu marca puede sostener.",
        framework: [
          "Nombre o código: frase breve que identifica la serie.",
          "Promesa: utilidad consistente en cada entrega.",
          "Estructura: apertura, desarrollo, prueba y cierre repetibles.",
          "Límite: qué entra y qué no entra para mantener identidad.",
        ],
        example: "“Te lo traduzco”: cada viernes toma un término de marketing, muestra cómo se usa mal, lo explica en lenguaje simple y cierra con una aplicación de diez minutos.",
        practice: "Diseña dos series por pilar. Escribe nombre, promesa, estructura, formato y diez episodios. Elimina series que no puedas sostener durante ocho semanas.",
        deliverable: "Ocho series editoriales con 80 ideas iniciales.",
      },
      {
        number: "08.3",
        title: "Formato, profundidad y reutilización",
        duration: "60 min",
        objective: "Elegir el formato por función comunicativa y no por moda.",
        concept: "El mismo tema puede cumplir tareas distintas. Un video breve abre curiosidad; un carrusel organiza pasos; una historia muestra contexto; un video largo profundiza; un correo crea intimidad. Reutilizar no es copiar y pegar: es conservar la idea y reconstruirla según comportamiento, tiempo y expectativa de cada formato.",
        framework: [
          "Idea núcleo: una afirmación que permanece en todas las versiones.",
          "Entrada nativa: gancho adaptado al entorno.",
          "Profundidad: cantidad de contexto necesaria para cumplir la promesa.",
          "Acción: siguiente paso coherente con el formato y la audiencia.",
        ],
        example: "Una entrevista de 30 minutos produce un video largo, tres clips con decisiones, un carrusel con el marco, un correo con la historia y cinco respuestas para comunidad. Cada pieza debe sentirse completa.",
        practice: "Elige una idea fuerte y crea un árbol de siete activos. Reescribe apertura, estructura y CTA para cada formato. No publiques fragmentos sin contexto.",
        deliverable: "Árbol de reutilización de una idea en siete piezas nativas.",
      },
      {
        number: "08.4",
        title: "Calendario de 30 días con intención",
        duration: "65 min",
        objective: "Organizar un mes alrededor de campañas, capacidad y aprendizaje.",
        concept: "El calendario no es una cuadrícula que debes llenar. Comienza con objetivo, campaña y capacidad. Distribuye funciones editoriales, series y formatos. Reserva espacio para respuesta rápida y aprendizaje. Cada publicación debe incluir hipótesis: qué audiencia, qué señal y qué decisión quieres observar.",
        framework: [
          "Tema mensual: una tensión central que conecta varias piezas.",
          "Cadencia: frecuencia mínima sostenible por formato.",
          "Campaña: secuencia de piezas que prepara una acción específica.",
          "Revisión: qué mantener, mejorar, convertir en serie o detener.",
        ],
        example: "Objetivo: conversaciones sobre auditoría. Semana 1 diagnostica, semana 2 enseña método, semana 3 demuestra casos y semana 4 resuelve objeciones e invita a aplicar.",
        practice: "Diseña 30 días con 12 a 16 piezas principales, historias de apoyo y ventanas de comunidad. Asigna objetivo, pilar, serie, formato, CTA y métrica a cada pieza.",
        deliverable: "Calendario editorial de 30 días y guía semanal de producción.",
      },
    ],
    mission: {
      title: "Sistema editorial de 90 días",
      brief: "Construye un sistema que transforme investigación en series y series en campañas medibles.",
      steps: [
        "Define cuatro pilares con funciones diferentes.",
        "Diseña ocho series y genera diez ideas por serie.",
        "Asigna formatos y árboles de reutilización.",
        "Planifica el primer mes alrededor de un objetivo.",
        "Crea una reunión editorial semanal de 30 minutos.",
      ],
      deliverable: "Mapa de pilares, banco de 80 ideas y calendario completo de 30 días.",
    },
    checklist: [
      "Cada pilar cumple una función estratégica.",
      "Las series son repetibles y reconocibles.",
      "Los formatos responden a una intención concreta.",
      "El calendario cabe en mi capacidad de producción.",
      "Cada pieza tiene una hipótesis y una métrica principal.",
    ],
    resources: [
      { title: "Mapa de pilares", type: "Plantilla", description: "Conecta problema, función, serie, formato, prueba y oferta." },
      { title: "Banco de series", type: "Tablero", description: "Gestiona promesas, estructuras, episodios y rendimiento de series." },
      { title: "Calendario de 30 días", type: "Plantilla", description: "Plan editorial con objetivo, CTA, responsable, estado y métrica." },
    ],
  },
  {
    number: "09",
    slug: "algoritmos",
    title: "Algoritmos",
    phase: "Mensaje y contenido",
    phaseNumber: "02",
    duration: "4 h",
    promise: "Comprender cómo funcionan los sistemas de recomendación para diseñar mejores señales sin perseguir trucos pasajeros.",
    summary: "No existe un único algoritmo ni una fórmula secreta. Las plataformas personalizan contenido usando información sobre el usuario, la pieza, el contexto y la respuesta observada. Este módulo traduce esos sistemas en decisiones prácticas: relevancia, retención, satisfacción, elegibilidad, empaque y experimentación. El objetivo es aprender a leer señales, no adivinar cambios.",
    outcomes: [
      "Entender la diferencia entre recomendación, búsqueda y distribución a seguidores.",
      "Diseñar contenido que produce señales de satisfacción y relevancia.",
      "Separar métricas de diagnóstico de métricas de ego.",
      "Crear experimentos controlados y tomar decisiones con suficiente evidencia.",
    ],
    lessons: [
      {
        number: "09.1",
        title: "Cómo piensa un sistema de recomendación",
        duration: "55 min",
        objective: "Reemplazar la idea de un algoritmo universal por un modelo práctico de selección y ranking.",
        concept: "Una plataforma reúne candidatos, predice cuáles pueden interesar a cada persona y los ordena. Las predicciones cambian según superficie: inicio, búsqueda, recomendados, Reels o Para Ti. La meta no es complacer una máquina; es producir una respuesta humana que el sistema pueda observar: elegir, mirar, continuar, guardar, compartir o volver.",
        framework: [
          "Candidato: qué piezas pueden mostrarse a esa persona.",
          "Relevancia: relación entre tema, usuario, contexto e historial.",
          "Rendimiento: qué ocurre cuando la pieza recibe una oportunidad.",
          "Satisfacción: señales explícitas e implícitas de valor a corto y largo plazo.",
        ],
        example: "Un video no es “bueno para el algoritmo” en abstracto. Puede ser relevante para consultores que buscan vender servicios y poco relevante para una audiencia general. Su empaque debe ayudar al sistema y al usuario a entender para quién es.",
        practice: "Elige una plataforma y dibuja tres superficies de descubrimiento. Para cada una, escribe intención del usuario, señales probables y qué debe comunicar el contenido antes de recibir interacción.",
        deliverable: "Mapa de distribución por plataforma y superficie.",
      },
      {
        number: "09.2",
        title: "Señales que sí puedes diseñar",
        duration: "60 min",
        objective: "Convertir relevancia y satisfacción en decisiones editoriales observables.",
        concept: "No controlas el ranking, pero controlas claridad del tema, fuerza del empaque, ritmo, cumplimiento de promesa y próximo paso. Las métricas deben interpretarse juntas. Mucha retención con comentarios confundidos puede indicar entretenimiento sin comprensión; muchos guardados y pocas reproducciones pueden revelar valor profundo con entrada débil.",
        framework: [
          "Elección: impresión a clic o inicio de reproducción.",
          "Consumo: tiempo visto, finalización y puntos de abandono.",
          "Valor: guardados, compartidos, respuestas y visitas relevantes.",
          "Continuidad: seguidores adecuados, siguiente pieza y retorno.",
        ],
        example: "Si una pieza tiene buena retención entre quienes comienzan pero pocas reproducciones, primero prueba empaque. Si abre fuerte pero cae en cinco segundos, corrige la entrega y elimina la introducción.",
        practice: "Analiza diez piezas. Registra tema, empaque, elección, retención, valor y continuidad. Escribe un diagnóstico y una sola mejora por pieza.",
        deliverable: "Tablero de señales con diagnóstico de diez contenidos.",
      },
      {
        number: "09.3",
        title: "Elegibilidad, originalidad y contexto",
        duration: "55 min",
        objective: "Proteger distribución comprendiendo que contenido permitido no siempre es recomendable.",
        concept: "Las plataformas aplican políticas adicionales a las recomendaciones. Contenido poco original, engañoso, sensible o de baja calidad puede ser elegible para permanecer y no para descubrirse. Revisa estado de cuenta, derechos, atribución y promesas. La originalidad no exige inventar un tema; exige aportar análisis, experiencia, demostración o contexto propio.",
        framework: [
          "Cumplimiento: normas de comunidad, propiedad intelectual y publicidad.",
          "Elegibilidad: estándares para llegar a personas que no te siguen.",
          "Originalidad: valor añadido que cambia comprensión o aplicación.",
          "Consistencia temática: señales claras sobre audiencia y territorio.",
        ],
        example: "Republicar un clip viral con subtítulos puede sumar poco valor. Analizar por qué funcionó, demostrar la estructura y aplicarla a tu industria convierte la referencia en una pieza original.",
        practice: "Audita 20 publicaciones por autoría, fuente, derechos, promesas, sensibilidad y aporte propio. Documenta un proceso de revisión antes de publicar.",
        deliverable: "Checklist de elegibilidad y protocolo de atribución.",
      },
      {
        number: "09.4",
        title: "Experimentación sin superstición",
        duration: "70 min",
        objective: "Aprender de datos sin atribuir cada variación a un cambio del algoritmo.",
        concept: "Una publicación está expuesta a tema, competencia, tamaño de muestra, estacionalidad, calidad, empaque y azar. Un experimento útil cambia una variable importante y repite suficientes veces. Evalúa tendencias de series, no el estado emocional causado por una sola pieza. Documenta hipótesis antes de ver el resultado.",
        framework: [
          "Hipótesis: si cambio X, espero Y porque Z.",
          "Control: conserva tema, formato o audiencia según la pregunta.",
          "Repetición: prueba varias piezas antes de concluir.",
          "Decisión: mantener, iterar, escalar o abandonar con criterio previo.",
        ],
        example: "Hipótesis: nombrar la situación del cliente en la primera línea aumentará retención inicial. Prueba seis videos de la misma serie, tres con contexto general y tres con situación específica.",
        practice: "Diseña un sprint de cuatro semanas con dos experimentos. Define variable, muestra mínima, métrica primaria, métrica de calidad y decisión posible.",
        deliverable: "Plan de experimentos y registro de aprendizajes por serie.",
      },
    ],
    mission: {
      title: "Laboratorio de distribución",
      brief: "Construye un sistema para diagnosticar contenido y mejorar señales sin perseguir rumores.",
      steps: [
        "Mapea superficies e intención de usuario en tu plataforma principal.",
        "Audita diez piezas con señales de elección, consumo, valor y continuidad.",
        "Revisa elegibilidad, derechos y originalidad.",
        "Diseña dos experimentos de cuatro semanas.",
        "Programa una revisión quincenal basada en series.",
      ],
      deliverable: "Tablero de señales, checklist de elegibilidad y sprint experimental.",
    },
    checklist: [
      "Sé qué superficie estoy optimizando.",
      "Interpreto señales en conjunto.",
      "Puedo distinguir un problema de empaque de uno de contenido.",
      "Reviso elegibilidad y originalidad antes de publicar.",
      "No saco conclusiones por una sola pieza.",
    ],
    resources: [
      { title: "Tablero de señales", type: "Tablero", description: "Métricas de elección, consumo, valor, continuidad y diagnóstico." },
      { title: "Protocolo experimental", type: "Plantilla", description: "Hipótesis, variable, muestra, métrica, resultado y decisión." },
      { title: "Recomendaciones en Instagram", type: "Referencia oficial", description: "Criterios de Meta sobre contenido y cuentas elegibles para recomendaciones.", href: "https://www.facebook.com/help/instagram/313829416281232" },
      { title: "Sistema de recomendaciones de YouTube", type: "Referencia oficial", description: "Explicación oficial sobre personalización, rendimiento y satisfacción.", href: "https://support.google.com/youtube/answer/16533387" },
      { title: "Cómo TikTok recomienda contenido", type: "Referencia oficial", description: "Factores y señales usados en los feeds de recomendación.", href: "https://support.tiktok.com/en/using-tiktok/exploring-videos/how-tiktok-recommends-content" },
    ],
  },
  {
    number: "10",
    slug: "guiones",
    title: "Guiones",
    phase: "Mensaje y contenido",
    phaseNumber: "02",
    duration: "4 h 15 min",
    promise: "Convertir ideas en guiones claros, naturales y filmables que sostienen atención y conducen a una acción.",
    summary: "Un buen guion no suena leído porque fue escrito para ser hablado. Aprenderás a partir de una idea y una audiencia, elegir estructura, escribir aperturas, desarrollar una sola promesa y cerrar con intención. También crearás sistemas para videos breves, clases, entrevistas y piezas de venta.",
    outcomes: [
      "Crear briefs que evitan escribir sin dirección.",
      "Dominar estructuras para videos breves, largos y educativos.",
      "Escribir en lenguaje oral con ritmo y transiciones naturales.",
      "Editar el guion antes de grabar para reducir tiempo y repeticiones.",
    ],
    lessons: [
      {
        number: "10.1",
        title: "El brief de una idea",
        duration: "50 min",
        objective: "Definir audiencia, promesa y acción antes de escribir líneas.",
        concept: "El bloqueo suele ser falta de decisiones. Un brief obliga a elegir una persona, un problema, una idea principal, una prueba y un siguiente paso. Si intentas incluir cinco aprendizajes, tendrás una lista, no una pieza. La restricción mejora claridad.",
        framework: [
          "Persona: quién necesita esta idea ahora.",
          "Promesa: qué entenderá o podrá hacer al terminar.",
          "Idea única: la frase que no puede perderse.",
          "Prueba y acción: evidencia principal y siguiente paso.",
        ],
        example: "Persona: consultor que explica demasiado. Promesa: simplificar su presentación. Idea: comienza con el problema que resuelves, no con tu currículum. Prueba: contraste de dos pitches. Acción: reescribir la primera frase.",
        practice: "Completa diez briefs de una página a partir del banco de ideas. Rechaza cualquier brief que no puedas resumir en una sola oración.",
        deliverable: "Diez briefs priorizados y listos para guion.",
      },
      {
        number: "10.2",
        title: "Guion de video breve",
        duration: "65 min",
        objective: "Sostener atención desde una entrada específica hasta un cierre completo.",
        concept: "El video breve necesita entrar cerca del valor. La apertura identifica situación y tensión; el puente aclara qué recibirás; el desarrollo entrega pocos pasos con ejemplos; el cierre resume y propone acción. Cada frase debe avanzar la idea, añadir prueba o mejorar comprensión.",
        framework: [
          "Gancho: situación, contraste o consecuencia específica.",
          "Puente: por qué importa y qué vas a demostrar.",
          "Valor: explicación, pasos y ejemplo visual.",
          "Cierre: síntesis y CTA proporcional.",
        ],
        example: "Gancho: “Si abres tus videos diciendo tu nombre y profesión, estás usando los segundos más caros para información que ya está en tu perfil”. Puente: “Haz esto”. Valor: muestra tres entradas. Cierre: invita a reescribir una.",
        practice: "Escribe cinco guiones de 45 a 75 segundos. Léelos en voz alta con cronómetro y elimina cualquier frase que repita la idea sin añadir valor.",
        deliverable: "Cinco guiones breves filmables con indicaciones visuales.",
      },
      {
        number: "10.3",
        title: "Guion largo, clase y video educativo",
        duration: "65 min",
        objective: "Organizar profundidad sin perder orientación ni ritmo.",
        concept: "El contenido largo necesita un mapa. Abre con promesa y ruta; divide en capítulos; alterna concepto, ejemplo y aplicación; usa resúmenes parciales; cierra integrando. La retención no depende de velocidad constante, sino de progreso visible y preguntas que se van resolviendo.",
        framework: [
          "Promesa y mapa: resultado y recorrido que seguirás.",
          "Capítulos: una pregunta central por bloque.",
          "Patrón pedagógico: explicar, mostrar, practicar y comprobar.",
          "Recapitulación: conecta cada parte con la transformación final.",
        ],
        example: "Una clase sobre posicionamiento puede dividirse en categoría, alternativa, diferencia y mensaje. Cada capítulo incluye diagnóstico, ejemplo de antes/después y ejercicio de aplicación.",
        practice: "Crea la escaleta de una clase de 20 minutos. Escribe apertura y cierre completos; en el desarrollo usa puntos, ejemplos, visuales y transiciones.",
        deliverable: "Escaleta de video largo con guion de apertura, transiciones y cierre.",
      },
      {
        number: "10.4",
        title: "Escritura oral, ensayo y teleprompter",
        duration: "75 min",
        objective: "Hacer que el guion suene como una conversación preparada, no como un documento leído.",
        concept: "El lenguaje hablado usa frases más cortas, repeticiones intencionales y conectores claros. Escribe para respirar. Marca palabras de énfasis, pausas, visuales y cambios de energía. El teleprompter no corrige un texto rígido: primero simplifica, luego ensaya por ideas y finalmente ajusta velocidad y distancia.",
        framework: [
          "Una respiración: una idea por frase.",
          "Palabras concretas: verbos y ejemplos antes que abstracciones.",
          "Marcación: pausa, énfasis, visual y corte.",
          "Ensayo: intención primero, memoria literal después.",
        ],
        example: "Texto escrito: “La implementación de una estrategia de posicionamiento requiere claridad conceptual”. Oral: “Posicionarte empieza por una decisión: ¿qué quieres que la gente recuerde cuando escucha tu nombre?”.",
        practice: "Graba una lectura del primer borrador. Marca tropiezos y frases sin aire. Reescribe, ensaya por bloques y vuelve a grabar comparando naturalidad, tiempo y claridad.",
        deliverable: "Guion final marcado y protocolo personal de ensayo.",
      },
    ],
    mission: {
      title: "Paquete de producción",
      brief: "Prepara una semana completa de guiones breves y una pieza larga conectada con la misma idea núcleo.",
      steps: [
        "Elige una idea núcleo y completa seis briefs.",
        "Escribe cinco guiones breves con ángulos diferentes.",
        "Crea una escaleta larga que profundice el tema.",
        "Añade indicaciones visuales, prueba y CTA.",
        "Haz lectura cronometrada y edita para oralidad.",
      ],
      deliverable: "Cinco guiones breves, una escaleta larga y protocolo de ensayo.",
    },
    checklist: [
      "Cada guion cumple una sola promesa.",
      "La apertura nombra una situación o tensión específica.",
      "El desarrollo incluye al menos un ejemplo.",
      "Las frases pueden decirse en una respiración.",
      "El CTA corresponde al nivel de confianza de la audiencia.",
    ],
    resources: [
      { title: "Brief de guion", type: "Plantilla", description: "Persona, promesa, idea, prueba, visual y acción antes del borrador." },
      { title: "Estructuras de video", type: "Guía", description: "Arquitecturas para video breve, caso, tutorial, opinión y clase." },
      { title: "Marcación de teleprompter", type: "Plantilla", description: "Sistema de pausas, énfasis, respiración, visuales y cortes." },
    ],
  },
];
